Part 1 — Inspect & Understand the Dataset
Q1. Load the dataset
Load messy_customer_analytics_2000x15.csv into a DataFrame called df.
Then display the first 10 rows.
Use: pd.read_csv(), head()

In [5]:
import pandas as pd
df=pd.read_csv(r"C:\Users\jyoti\Downloads\customer_analytics.csv")
print(df)
df.head(10)

      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2040 rows x 15 columns]

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68.0,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47.0,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65.0,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63.0,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42.0,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

Q2. Inspect the end of the dataset
Display the last 15 rows.
Use: tail()

In [6]:
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51.0,214004.0,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573.0,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54.0,123511.0,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31.0,125500.0,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619.0,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41.0,201611.0,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61.0,128850.0,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33.0,88037.0,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43.0,122756.0,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18.0,189232.0,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

Q3. Random inspection
Display 10 random records.
Use: sample()

In [7]:
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1846,100564,NaN,221910.0,68608.32,724,13,NaN,Corporate,Online,2024-02-06 00:00:00,Yes,Low,625.11,137,4.7
972,101647,27.0,207779.0,NaN,331,0,Delhi,Premium,Branch,2021-06-01 00:00:00,No,High,6575.63,unknown,NaN
739,100590,65.0,228532.0,109306.27,470,7,Delhi,Premium,Online,2021-11-13 00:00:00,No,High,42773.04,28,1.0
523,101101,32.0,28631.0,130925.88,624,2,Mumbai,Premium,Branch,2022-12-28 00:00:00,Yes,Medium,13411.34,116,6.0
902,101895,-,106768.0,171792.86,590,9,Bangalore,Corporate,Mobile,NaN,N,Medium,31999.23,116,1.6
1620,101073,abc,145575.0,158617.33,768,5,Kolkata,Corporate,Mobile,2023-06-12 00:00:00,Yes,Low,22645.3,127,7.5
1674,101698,74.0,130487.0,99599.49,836,2,Kolkata,SME,Branch,2022-03-25 00:00:00,Yes,Low,26853.74,71,5.6
455,101680,38.0,NaN,169821.49,351,15,Pune,Premium,Mobile,2024-11-05 00:00:00,Yes,High,18225.22,28,3.7
1538,100838,36.0,156733.0,148050.3,431,1,Mumbai,Corporate,Mobile,2025-10-31 00:00:00,Yes,High,34900.89,111,7.5
86,101478,35.0,179324.0,13574.76,610,9,Kolkata,Corporate,Mobile,2025-10-16 00:00:00,Yes,High,9815.12,37,3.9

Q4. Dataset audit
Use info() to identify:
• Number of rows
• Number of columns
• Columns with missing values
• Columns having incorrect/object datatypes
Use: info()

df.info()

Q5. Missing-value audit
Calculate the number of missing values in every column.
Then verify the result using both:
isnull()
and
isna()

In [15]:
print(df.isnull().sum())
print(df.isnull().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

Part 2 — Detect & Fix Data Quality Problems
Q6. Duplicate investigation
Find how many duplicate rows exist.
Do not remove them yet.
Use: duplicated()

In [17]:
print(df.duplicated().sum())# to find  the no of duplicate rows

40

Q7. Remove duplicates
Remove all duplicate records and store the cleaned result back into df.
Then verify that duplicates no longer exist.
Use: drop_duplicates(), duplicated()

In [23]:
df=df.drop_duplicates()
print(df)
df.duplicated()

      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2000 rows x 15 columns]

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2000, dtype: bool

Q8. Numeric column investigation
Select only numeric columns.
Identify which columns are currently numeric and which potentially numeric columns have
become object because of invalid values.
Use: select_dtypes()

In [44]:
num=df.select_dtypes(["number"])
print("currently numeric")
print(num)
print("potentially numeric columns have become object because of invalid values.")
obj=df.select_dtypes(include=["object"])
print(obj)

currently numeric
      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]
potentially numeric columns have become object because of invalid values.
       Age Annual_Income Account_Balance Credit_Score         City    Segment  \
0     55.0       44033.0       111350.85          772    Bangalore        SME
1     32.0      215546.0       254378.37          374        Delhi     Retail
2     23.0      226403.0       159975.42          668      Chennai    Premium
3     66.0       87824.0        295741.6          315       Mumbai    Premium
4     67.0       31570.0       242423.78          370   bangalore      Retail
...    ...           ...             ...          ...          ...        ...
2035  42.0       88530.0       153490.72          677    Hyderabad     Retail
2036  31.0      205738.0        270989.4          392       Mumbai  Corporate
2037  25.0      211994.0       160507.65          737      Kolkata     Retail
2038  64.0       30105.0        32117.15          794    Bangalore     Retail
2039  55.0      248332.0       274980.99          783      Chennai     Retail

     Channel            Join_Date Active Risk_Level Monthly_Spend Transactions
0      Agent  2022-08-15 00:00:00    Yes        Low      23066.19          135
1      Agent  2025-01-11 00:00:00    Yes       High           NaN          106
2      Agent  2024-08-01 00:00:00     No     Medium      28536.34          146
3      Agent  2021-05-15 00:00:00    Yes       High      12869.71          115
4      Agent  2026-02-03 00:00:00     No       High      34163.02           94
...      ...                  ...    ...        ...           ...          ...
2035   Agent  2021-07-10 00:00:00     No     Medium       8455.42          119
2036   Agent  2025-07-05 00:00:00    Yes       High      34087.69          134
2037  Online  2022-10-17 00:00:00    Yes        Low      26518.74           87
2038   Agent  2023-08-26 00:00:00     No        Low      20943.11          107
2039  Branch                  NaN    Yes        Low      48511.32          119

[2000 rows x 12 columns]

Q9. Fix Age
The Age column contains:
• Valid numbers
• Missing values
• Invalid text such as unknown, N/A, etc.
Convert Age into a proper numeric column.
Invalid values should become missing values.
Then fill missing Age values using the median age.
Use: pd.to_numeric(), median(), fillna()

In [52]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
print(df["Age"])
print("finding meadian of Age")
median=df["Age"].median()
print(median)
print("filling missing value of age with  median")
df["Age"]=df["Age"].fillna(median)
print(df["Age"])

0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64
finding meadian of Age
47.0
filling missing value of age with  median
0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: Age, Length: 2000, dtype: float64

Q10. Fix Annual Income
Clean Annual_Income.
Requirements:
1. Convert invalid values to missing.
2. Convert the column to a numeric datatype.
3. Calculate the median.
4. Fill missing values using the median.
Use: pd.to_numeric(), median(), fillna(), astype()

In [59]:
df["Annual_Income"]=pd.to_numeric(df["Annual_Income"],errors="coerce")
print(df["Annual_Income"])
print("calculating median of Annual_Income")
median=df["Annual_Income"].median()
print(median)
print("  missing values is filled  using  median")
df["Annual_Income"]=df["Annual_Income"].fillna(median)
print(df["Annual_Income"])

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2000, dtype: float64
calculating median of Annual_Income
139914.0
  missing values is filled  using  median
0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2000, dtype: float64

In [ ]:
Part 3 — Numerical Cleaning
Q11. Clean Account Balance
The Account_Balance column contains invalid strings and missing values.
Clean the column and replace missing values with the mean Account Balance.
Use:
• pd.to_numeric()
• mean()
• fillna()

In [63]:
df["Account_Balance"]=pd.to_numeric(df["Account_Balance"],errors="coerce")
print(df["Account_Balance"])
mean=df["Account_Balance"].mean()
print("mean of Account balance:")
print(mean)
print("filling missing values with mean")
df["Account_Balance"]=df["Account_Balance"].fillna(mean)
print(df["Account_Balance"])

0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2000, dtype: float64
mean of Account balance:
151344.55801855895
filling missing values with mean
0       111350.85
1       254378.37
2       159975.42
3       295741.60
4       242423.78
          ...
2035    153490.72
2036    270989.40
2037    160507.65
2038     32117.15
2039    274980.99
Name: Account_Balance, Length: 2000, dtype: float64

Q12. Clean Credit Score
Clean Credit_Score.
Invalid values should become missing.
Then replace missing values with the median Credit Score.
Finally convert the column to integer.
Use:
• pd.to_numeric()
• median()

• fillna()
• astype()

In [69]:
df["Credit_Score"]=pd.to_numeric(df["Credit_Score"],errors="coerce")
print("filling invalid values to missing")
print(df["Credit_Score"])
print("finding median of credit score")
median=df["Credit_Score"].median()
print(median)
print("replacing missing values with median score")
df["Credit_Score"]=df["Credit_Score"].fillna(median)
print(df["Credit_Score"])
print(" converting columns to integer")
df["Credit_Score"]=df["Credit_Score"].astype("int")
print(df["Credit_Score"])

filling invalid values to missing
0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: Credit_Score, Length: 2000, dtype: float64
finding median of credit score
570.5
replacing missing values with median score
0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: Credit_Score, Length: 2000, dtype: float64
 converting columns to integer
0       772
1       374
2       668
3       315
4       370
       ...
2035    677
2036    392
2037    737
2038    794
2039    783
Name: Credit_Score, Length: 2000, dtype: int64

Q13. Clean Monthly Spend
Clean Monthly_Spend.
Then:
• Convert it to numeric.
• Replace invalid values.
• Replace missing values using the median.
• Make sure the final column is numeric.

In [72]:
df["Monthly_Spend"]=pd.to_numeric(df["Monthly_Spend"],errors="coerce")
print(df["Monthly_Spend"])
median=df["Monthly_Spend"].median()
print("finding median of Monthly_Spend :")
print(median)
print("replacing missing value  with median")
df["Monthly_Spend"]=df["Monthly_Spend"].fillna(median)
print(df["Monthly_Spend"])

0       23066.19
1            NaN
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2000, dtype: float64
finding median of Monthly_Spend :
24625.17
replacing missing value  with median
0       23066.19
1       24625.17
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2000, dtype: float64

Q14. Clean Transactions
The Transactions column contains invalid strings.
Convert it to numeric and replace invalid values with the median number of transactions.
Then convert the final column to integer.

In [78]:
df["Transactions"]=pd.to_numeric(df["Transactions"],errors="coerce")
print("converting the values to numeric values and invalid  values to  missing values")
print(df["Transactions"])
print(" finding the median of  Transactions")
median=df["Transactions"].median()
print(median)
print(" replacing missing values with median")
df["Transactions"]=df["Transactions"].fillna(median)
print(df["Transactions"])
print("converting the column to integer")
df["Transactions"]=df["Transactions"].astype("int")
print(df["Transactions"])

converting the values to numeric values and invalid  values to  missing values
0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2000, dtype: float64
 finding the median of  Transactions
76.0
 replacing missing values with median
0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2000, dtype: float64
converting the column to integer
0       135
1       106
2       146
3       115
4        94
       ...
2035    119
2036    134
2037     87
2038    107
2039    119
Name: Transactions, Length: 2000, dtype: int64

Q15. Clean Satisfaction Score
Clean Satisfaction_Score.
Replace missing/invalid values using the mean Satisfaction Score.
Then convert the column to float.

In [81]:
df["Satisfaction_Score"]=pd.to_numeric(df["Satisfaction_Score"],errors="coerce")
print(df["Satisfaction_Score"])
print('finding mean of this column')
mean=df["Satisfaction_Score"].mean()
print(mean)
print('Replace missing/invalid values using the mean Satisfaction Score')
df["Satisfaction_Score"]=df["Satisfaction_Score"].fillna(mean)
print(df["Satisfaction_Score"])
print("converting the column to float")
df["Satisfaction_Score"]=df["Satisfaction_Score"].astype("float")
print(df["Satisfaction_Score"])

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64
finding mean of this column
5.605416666666668
eplace missing/invalid values using the mean Satisfaction Score
0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64
converting the column to float
0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64

In [ ]:
Part 4 — Date Cleaning
Q16. Investigate Join_Date
Inspect the Join_Date column.
Identify the problems caused by:
• Missing dates
• Different date formats
• Invalid date strings

Do not clean it yet.

In [88]:
print(" inspecting join date column")
print(df["Join_Date"])
print(" identifying  number missing dates of column")
print(df["Join_Date"].isnull().sum())
print(" diffrent date format")
print(df["Join_Date"].dtype)
print("invalid date string")
print(df["Join_Date"].unique())

 inspecting join date column
0       2022-08-15 00:00:00
1       2025-01-11 00:00:00
2       2024-08-01 00:00:00
3       2021-05-15 00:00:00
4       2026-02-03 00:00:00
               ...
2035    2021-07-10 00:00:00
2036    2025-07-05 00:00:00
2037    2022-10-17 00:00:00
2038    2023-08-26 00:00:00
2039                    NaN
Name: Join_Date, Length: 2000, dtype: object
 identifying  number missing dates of column
100
 diffrent date format
object
invalid date string
['2022-08-15 00:00:00' '2025-01-11 00:00:00' '2024-08-01 00:00:00' ...
 '2025-09-10 00:00:00' '2022-10-17 00:00:00' '2023-08-26 00:00:00']

Q17. Convert Join_Date
Convert Join_Date into a proper Pandas datetime column.
Any invalid dates should become missing values.
Use: pd.to_datetime()

In [91]:
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
print(df["Join_Date"])

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039          NaT
Name: Join_Date, Length: 2000, dtype: datetime64[ns]

Q18. Handle missing dates
After conversion, find how many missing dates remain.
Then replace missing dates appropriately using a reasonable date-based strategy.

In [103]:
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
print(" number of missing values:")
print(df["Join_Date"].isnull().sum())
print("replacing missing dates appropriately using a reasonable date-based strategy.")
median=df["Join_Date"].median()
print(f"median of this column is {median}")
print("filling the missing values with median")

df["Join_Date"].fillna(median)

 number of missing values:
125
replacing missing dates appropriately using a reasonable date-based strategy.
median of this column is 2023-08-24 00:00:00
filling the missing values with median

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039   2023-08-24
Name: Join_Date, Length: 2000, dtype: datetime64[ns]

Part 5 — Categorical Cleaning
Q19. Clean City
The City column contains values such as:
Mumbai
mumbai
Mumbai
mumbai
Standardize the values so that logically identical cities are represented consistently.
Then check the unique frequency distribution.
Use: replace(), value_counts()

Series([], Name: count, dtype: int64)

Q20. Analyze Segment
Check the frequency of:
Retail
SME
Corporate
Premium
Also determine whether missing values exist.
Then replace missing Segment values with the most appropriate category based on your
analysis.

In [127]:
print(" finding frequency")
df["Segment"].value_counts() 
print(" number of missing values:")
print(df["Segment"].isnull().sum())
mode=df["Segment"].mode()[0] 
print("mode of this column:")
print(mode)
print(" after filling missing values with mode")
df["Segment"].fillna(mode)# as this is catagorial data  the missing values will be  filled using mode

 finding frequency
 number of missing values:
100
mode of this column:
Premium
 after filling missing values with mode

0             SME
1          Retail
2         Premium
3         Premium
4          Retail
          ...
2035       Retail
2036    Corporate
2037       Retail
2038       Retail
2039       Retail
Name: Segment, Length: 2000, dtype: object

Q21. Clean Active
Active is supposed to be a binary column, but it contains:
Yes
No
Y
N
YES
NO
yes
no
1
0
Transform these into a consistent representation:
Yes
No
Then verify the result with value_counts().
Use: replace(), value_counts()

In [136]:
df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    1: "Yes",
    "1": "Yes",
    "N": "No",
    "NO": "No",
    "no": "No",
    0: "No",
    "0": "No"
})

print("Unique values:")
print(df["Active"].unique())

print("\nValue counts:")
print(df["Active"].value_counts())

Unique values:
['Yes' 'No' nan]

Value counts:
Active
Yes    1345
No      597
Name: count, dtype: int64

In [ ]:
Q22. Clean Risk_Level
Check the distribution of:
High
Medium
Low
Verify whether missing values exist.qa
Then display the final class distribution.

In [144]:
print(f" distribution of each element in column is  :\n{df["Risk_Level"].value_counts()}")#to check distribution of each element in column
print(" number missing values in this column is :")
print(df["Risk_Level"].isnull().sum())
print(" final class distribution")
df["Risk_Level"].value_counts()

 distribution of each element in column is  :
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64
 number missing values in this column is :
0
 final cladd distribution

Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64

Part 6 — Column Transformation
Q23. Rename columns
Rename these columns:
Customer_ID → Customer_ID
Annual_Income → AnnualIncome
Account_Balance → AccountBalance
Credit_Score → CreditScore
Tenure_Years → Tenure
Join_Date → CustomerJoinDate
Risk_Level → RiskLevel
Monthly_Spend → MonthlySpend
Satisfaction_Score → SatisfactionScore
Use rename().

In [146]:
df.rename(columns={"Customer_ID":"Customer_ID","Account_Balance":"AccountBalance","Credit_Score":"CreditScore","Tenure_Years":"Tenure","Join_Date":"CustomerJoinDate"\
                    ,"Risk_Level":"RiskLevel","Monthly_Spend":"MonthlySpend","Satisfaction_Score":"SatisfactionScore"})

,Customer_ID,Age,Annual_Income,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55.0,44033.0,111350.85,772,3,None,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,None,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,None,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,None,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,None,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,None,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392,8,None,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,None,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,None,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,None,Retail,Branch,NaT,Yes,Low,48511.32,119,3.1

Q24. Add a prefix
Add:
Customer_
to every column.
Example:
Age
becomes:
Customer_Age
Use: add_prefix()

In [148]:
df.add_prefix("Customer_")

,Customer_Customer_ID,Customer_Age,Customer_Annual_Income,Customer_Account_Balance,Customer_Credit_Score,Customer_Tenure_Years,Customer_City,Customer_Segment,Customer_Channel,Customer_Join_Date,Customer_Active,Customer_Risk_Level,Customer_Monthly_Spend,Customer_Transactions,Customer_Satisfaction_Score
0,101317,55.0,44033.0,111350.85,772,3,None,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,101001,32.0,215546.0,254378.37,374,8,None,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,101069,23.0,226403.0,159975.42,668,12,None,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,101968,66.0,87824.0,295741.60,315,14,None,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,100530,67.0,31570.0,242423.78,370,4,None,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42.0,88530.0,153490.72,677,12,None,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,101295,31.0,205738.0,270989.40,392,8,None,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,100861,25.0,211994.0,160507.65,737,8,None,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,101460,64.0,30105.0,32117.15,794,8,None,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,101127,55.0,248332.0,274980.99,783,6,None,Retail,Branch,NaT,Yes,Low,48511.32,119,3.1

In [ ]:
Q25. Remove unnecessary column

Determine whether Customer_ID should be retained for analysis.
Create a cleaned DataFrame without the identifier column.
Use: drop()

In [150]:
df.drop(columns=["Customer_ID"])

,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,55.0,44033.0,111350.85,772,3,None,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,32.0,215546.0,254378.37,374,8,None,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,23.0,226403.0,159975.42,668,12,None,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,66.0,87824.0,295741.60,315,14,None,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,67.0,31570.0,242423.78,370,4,None,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42.0,88530.0,153490.72,677,12,None,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,31.0,205738.0,270989.40,392,8,None,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,25.0,211994.0,160507.65,737,8,None,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,64.0,30105.0,32117.15,794,8,None,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,55.0,248332.0,274980.99,783,6,None,Retail,Branch,NaT,Yes,Low,48511.32,119,3.1

Part 7 — Create New Columns
Q26. Create Annual Income in Lakhs
Create:
Income_Lakhs
using:
AnnualIncome / 100000
Then check the first 10 records.

In [154]:
df["Income_Lakhs"]=df["Annual_Income"]/100000
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs
0,101317,55.0,44033.0,111350.85,772,3,None,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1,0.44033
1,101001,32.0,215546.0,254378.37,374,8,None,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2,2.15546
2,101069,23.0,226403.0,159975.42,668,12,None,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3,2.26403
3,101968,66.0,87824.0,295741.60,315,14,None,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7,0.87824
4,100530,67.0,31570.0,242423.78,370,4,None,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7,0.31570
5,101334,68.0,37087.0,180084.44,738,1,None,Premium,Agent,2023-06-04,Yes,Low,15121.16,6,8.5,0.37087
6,100415,47.0,67229.0,99629.81,464,4,None,Retail,Online,2024-01-16,Yes,High,17655.61,31,2.8,0.67229
7,100983,65.0,139914.0,61030.94,554,15,None,SME,Agent,2024-06-26,Yes,Medium,1720.85,139,9.7,1.39914
8,100417,63.0,153267.0,221707.97,508,5,None,Premium,Mobile,2025-03-12,Yes,High,38043.07,76,7.1,1.53267
9,101472,42.0,139914.0,41126.84,556,3,None,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124,9.1,1.39914

Q27. Create Monthly Income
Create:
MonthlyIncome
using:
AnnualIncome / 12
Then create:
Income_After_Spending
using:
MonthlyIncome - MonthlySpend

In [160]:
df["MonthlyIncome"]=df["Annual_Income"]/12#new column "MonthlyIncome" created
df["Income_After_Spending"]=df["MonthlyIncome"]-df["Monthly_Spend"] #new column "Income_After_Spending" created
print(df.head(10))# to verify new  columns

   Customer_ID   Age  Annual_Income  Account_Balance  Credit_Score  \
0       101317  55.0        44033.0        111350.85           772
1       101001  32.0       215546.0        254378.37           374
2       101069  23.0       226403.0        159975.42           668
3       101968  66.0        87824.0        295741.60           315
4       100530  67.0        31570.0        242423.78           370
5       101334  68.0        37087.0        180084.44           738
6       100415  47.0        67229.0         99629.81           464
7       100983  65.0       139914.0         61030.94           554
8       100417  63.0       153267.0        221707.97           508
9       101472  42.0       139914.0         41126.84           556

   Tenure_Years  City    Segment Channel  Join_Date Active Risk_Level  \
0             3  None        SME   Agent 2022-08-15    Yes        Low
1             8  None     Retail   Agent 2025-01-11    Yes       High
2            12  None    Premium   Agent 2024-08-01     No     Medium
3            14  None    Premium   Agent 2021-05-15    Yes       High
4             4  None     Retail   Agent 2026-02-03     No       High
5             1  None    Premium   Agent 2023-06-04    Yes        Low
6             4  None     Retail  Online 2024-01-16    Yes       High
7            15  None        SME   Agent 2024-06-26    Yes     Medium
8             5  None    Premium  Mobile 2025-03-12    Yes       High
9             3  None  Corporate  Mobile 2021-10-07    Yes     Medium

   Monthly_Spend  Transactions  Satisfaction_Score  Income_Lakhs  \
0       23066.19           135                 3.1       0.44033
1       24625.17           106                 8.2       2.15546
2       28536.34           146                 6.3       2.26403
3       12869.71           115                 9.7       0.87824
4       34163.02            94                 3.7       0.31570
5       15121.16             6                 8.5       0.37087
6       17655.61            31                 2.8       0.67229
7        1720.85           139                 9.7       1.39914
8       38043.07            76                 7.1       1.53267
9       11472.36           124                 9.1       1.39914

   MonthlyIncome  Income_After_Spending
0    3669.416667          -19396.773333
1   17962.166667           -6663.003333
2   18866.916667           -9669.423333
3    7318.666667           -5551.043333
4    2630.833333          -31532.186667
5    3090.583333          -12030.576667
6    5602.416667          -12053.193333
7   11659.500000            9938.650000
8   12772.250000          -25270.820000
9   11659.500000             187.140000

Q28. Create Balance-to-Income Ratio
Create:
Balance_Income_Ratio
using:
AccountBalance / AnnualIncome
Then inspect the first 10 rows.
Think carefully about division by zero and missing values.

In [163]:
try:
    df["Balance_Income_Ratio"]=df["Account_Balance"]/df["Annual_Income"]
    print(df.head(10))
except Exception as e:
    print(e)

   Customer_ID   Age  Annual_Income  Account_Balance  Credit_Score  \
0       101317  55.0        44033.0        111350.85           772
1       101001  32.0       215546.0        254378.37           374
2       101069  23.0       226403.0        159975.42           668
3       101968  66.0        87824.0        295741.60           315
4       100530  67.0        31570.0        242423.78           370
5       101334  68.0        37087.0        180084.44           738
6       100415  47.0        67229.0         99629.81           464
7       100983  65.0       139914.0         61030.94           554
8       100417  63.0       153267.0        221707.97           508
9       101472  42.0       139914.0         41126.84           556

   Tenure_Years  City    Segment Channel  Join_Date Active Risk_Level  \
0             3  None        SME   Agent 2022-08-15    Yes        Low
1             8  None     Retail   Agent 2025-01-11    Yes       High
2            12  None    Premium   Agent 2024-08-01     No     Medium
3            14  None    Premium   Agent 2021-05-15    Yes       High
4             4  None     Retail   Agent 2026-02-03     No       High
5             1  None    Premium   Agent 2023-06-04    Yes        Low
6             4  None     Retail  Online 2024-01-16    Yes       High
7            15  None        SME   Agent 2024-06-26    Yes     Medium
8             5  None    Premium  Mobile 2025-03-12    Yes       High
9             3  None  Corporate  Mobile 2021-10-07    Yes     Medium

   Monthly_Spend  Transactions  Satisfaction_Score  Income_Lakhs  \
0       23066.19           135                 3.1       0.44033
1       24625.17           106                 8.2       2.15546
2       28536.34           146                 6.3       2.26403
3       12869.71           115                 9.7       0.87824
4       34163.02            94                 3.7       0.31570
5       15121.16             6                 8.5       0.37087
6       17655.61            31                 2.8       0.67229
7        1720.85           139                 9.7       1.39914
8       38043.07            76                 7.1       1.53267
9       11472.36           124                 9.1       1.39914

   MonthlyIncome  Income_After_Spending  Balance_Income_Ratio
0    3669.416667          -19396.773333              2.528805
1   17962.166667           -6663.003333              1.180158
2   18866.916667           -9669.423333              0.706596
3    7318.666667           -5551.043333              3.367435
4    2630.833333          -31532.186667              7.678929
5    3090.583333          -12030.576667              4.855730
6    5602.416667          -12053.193333              1.481947
7   11659.500000            9938.650000              0.436203
8   12772.250000          -25270.820000              1.446547
9   11659.500000             187.140000              0.293944

Part 8 — Final Real-World Cleaning Challenge
Q29. Prepare the ML-ready dataset
Perform the following complete pipeline:
1. Load the dataset.
2. Inspect the first 10 rows.
3. Inspect the last 10 rows.
4. Inspect 10 random records.
5. Run info().
6. Check missing values.
7. Check duplicates.
8. Remove duplicates.
9. Clean all numeric columns.
10. Convert invalid numeric values to missing.
11. Fill numerical missing values appropriately.
12. Convert Join_Date to datetime.
13. Handle invalid dates.
14. Standardize categorical values.
15. Clean the binary Active column.
16. Rename the columns.
17. Remove unnecessary columns.
18. Verify the final datatypes.
19. Generate descriptive statistics.
20. Check categorical distributions.

In [235]:
print("loading dataset:")
import pandas as pd
df=pd.read_csv(r"C:\Users\jyoti\Downloads\customer_analytics.csv")
print(df)
print(" inspecting first 10 rowa")
print(df.head(10))
print("inspecting last 10 rowa")
print(df.tail(10))
print(f" last 10 random records:\n{df.sample(10)}")
print("information  of the dataset")
print(df.info())
print("missing values")
print(df.isnull().sum())
print("checking duplicates")
print(df.duplicated().sum())
print("after removing duplicates")
df=df.drop_duplicates()
print(df)
print("1.cleaning numeric column")
print(" numeric column ")
num=df.select_dtypes(["number"])
print(num)
print(" finding missing value of each numeric columns")
print(num.isnull().sum())
print("filling missing values with median")
median=df["Satisfaction_Score"].median()
print("median of  Satisfaction_Score is" ,median)
df["Satisfaction_Score"]=df["Satisfaction_Score"].fillna(median)
print(f"after cleaning dataset by  replacing median in missing value{df['Satisfaction_Score']}")
print("finding object column in  data")
obj=df.select_dtypes(["object"]).columns
print(obj)
print(" suspecting  columns which contain invalid data")
for col in obj:
     print(f"{col}:")
     print(df[col].unique())
print(" converting invalid values to missing values in  columns df['Age'],df['Credit_Score'],df['Transactions]") 
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Credit_Score"]=pd.to_numeric(df["Credit_Score"],errors="coerce")
df["Transactions"]=pd.to_numeric(df["Transactions"],errors="coerce")
print(f'{df["Age"]}\n{df["Credit_Score"]}\n{df["Transactions"]}\n')
print( " median of each  above column to  fill the missing values")
median_creditscore=df["Credit_Score"].median()
median_Age=df["Age"].median()
median_Transactions=df["Transactions"].median()
print("filling missing values of  column with its respective values")
df["Credit_Score"]=df["Credit_Score"].fillna(median_creditscore)
df["Age"]=df["Age"].fillna(median_Age)
df["Transactions"]=df["Transactions"].fillna(median_Transactions)
print(" after filling missing value of column age, transaction and ctreditscore")
print(df["Age"])
print(df["Transactions"])
print(df["Credit_Score"])
print("Converting Join_Date to datetime")
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
print(df["Join_Date"])
print(" finding catagorigal value")
df.columns
print('among columns previously we found catagorcal values are "City","Segment","Channel","Active","Risk_Level"')
print("value count of or distribution of values of each column")
print(df["City"].value_counts())
print(df["Segment"].value_counts())
print(df["Channel"].value_counts())
print("Standardize categorical values of each column")
print("already have unique values so no standardisation need in these catagorical value")
print(" Renaming columns")
df=df.rename(columns={"Customer_ID":"customer_id","Age":"age","Annual_Income" :"anuual_income","Account_Balance":"account_balance","Credit_Score":"credit_score","Tenure_Years":"tenure_year","City":"city","Segment":"segment" } )
print(df)
print("verifying final datatypes")
df.dtypes
print("escriptive statistics")
df.describe()
obj=df.select_dtypes(["object"])
print(f"checking catagirical data{obj}")

loading dataset:
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2040 rows x 15 columns]
 inspecting first 10 rowa
   Customer_ID   Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55.0       44033.0       111350.85          772             3
1       101001  32.0      215546.0       254378.37          374             8
2       101069  23.0      226403.0       159975.42          668            12
3       101968  66.0       87824.0        295741.6          315            14
4       100530  67.0       31570.0       242423.78          370             4
5       101334  68.0       37087.0       180084.44          738             1
6       100415  47.0       67229.0        99629.81          464             4
7       100983  65.0           NaN        61030.94          554            15
8       100417  63.0      153267.0       221707.97          508             5
9       101472  42.0       missing        41126.84          556             3

          City    Segment Channel            Join_Date Active Risk_Level  \
0    Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1        Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2      Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3       Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4   bangalore      Retail   Agent  2026-02-03 00:00:00     No       High
5      Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6      Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7      Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8    Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9      Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7
5      15121.16            6                 8.5
6      17655.61           31                 2.8
7       1720.85          139                 9.7
8      38043.07           76                 7.1
9      11472.36          124                 9.1
inspecting last 10 rowa
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
2030       100122  41.0      201611.0        40736.71          507
2031       101639  61.0      128850.0        266135.8          840
2032       101045  33.0       88037.0       129948.93          449
2033       101725  43.0      122756.0        36633.45          487
2034       101096  18.0      189232.0       235131.72          306
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
2030            15    Bangalore        SME   Agent  2024-11-03 00:00:00
2031             9      Kolkata        SME  Mobile  2026-01-15 00:00:00
2032             8       Mumbai    Premium  Mobile  2022-11-30 00:00:00
2033             8         Pune        NaN  Mobile  2021-07-04 00:00:00
2034            10   hyderabad         SME  Mobile  2025-09-10 00:00:00
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
2030    Yes       High       18815.18           58                 7.2
2031    Yes        Low       34300.44           83                 5.0
2032    Yes       High  not_available          147                 9.7
2033     No       High       10165.71           14                 6.4
2034     No       High       27227.44           85                 5.9
2035     No     Medium        8455.42          119                 8.6
2036    Yes       High       34087.69          134                 2.6
2037    Yes        Low       26518.74           87                 1.3
2038     No        Low       20943.11          107                 9.3
2039    Yes        Low       48511.32          119                 3.1
 last 10 random records:
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
903        100669  28.0       64310.0       199543.86          514
151        100619  72.0      125494.0        57335.61          709
1538       100838  36.0      156733.0        148050.3          431
2001       101585  64.0       99071.0        28718.72          475
354        100528  33.0       81503.0       241425.94          481
739        100590  65.0      228532.0       109306.27          470
1705       100346  41.0       97715.0       283194.69          443
1391       100279  69.0       99441.0       174977.25          586
917        100821  55.0      224083.0               -          771
744        100286  50.0       31368.0       227883.43          314

      Tenure_Years       City    Segment Channel            Join_Date Active  \
903              1  Hyderabad  Corporate  Branch                  NaN    Yes
151             11     Mumbai     Retail  Mobile  2025-11-22 00:00:00    Yes
1538             1     Mumbai  Corporate  Mobile  2025-10-31 00:00:00    Yes
2001             2    Chennai        SME  Branch                  NaN    Yes
354             12    Kolkata    Premium  Online  2022-05-30 00:00:00     No
739              7      Delhi    Premium  Online  2021-11-13 00:00:00     No
1705             0     Mumbai        SME  Online  2025-01-31 00:00:00    Yes
1391             6    Chennai  Corporate  Online  2023-03-29 00:00:00    NaN
917             12  Hyderabad        SME  Branch  2022-10-12 00:00:00     No
744             14    Kolkata  Corporate   Agent  2023-07-14 00:00:00    Yes

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
903        High      25569.83           53                 8.4
151         Low           NaN           23                 4.3
1538       High      34900.89          111                 7.5
2001       High           NaN           42                 3.3
354        High      38234.78           46                 3.7
739        High      42773.04           28                 1.0
1705       High      34926.04           10                 4.9
1391     Medium       9856.34          112                 1.4
917         Low      43187.83            6                 1.4
744        High      33257.38           25                 7.6
information  of the dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
None
missing values
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
checking duplicates
40
after removing duplicates
      Customer_ID   Age Annual_Income Account_Balance Credit_Score  \
0          101317  55.0       44033.0       111350.85          772
1          101001  32.0      215546.0       254378.37          374
2          101069  23.0      226403.0       159975.42          668
3          101968  66.0       87824.0        295741.6          315
4          100530  67.0       31570.0       242423.78          370
...           ...   ...           ...             ...          ...
2035       101131  42.0       88530.0       153490.72          677
2036       101295  31.0      205738.0        270989.4          392
2037       100861  25.0      211994.0       160507.65          737
2038       101460  64.0       30105.0        32117.15          794
2039       101127  55.0      248332.0       274980.99          783

      Tenure_Years         City    Segment Channel            Join_Date  \
0                3    Bangalore        SME   Agent  2022-08-15 00:00:00
1                8        Delhi     Retail   Agent  2025-01-11 00:00:00
2               12      Chennai    Premium   Agent  2024-08-01 00:00:00
3               14       Mumbai    Premium   Agent  2021-05-15 00:00:00
4                4   bangalore      Retail   Agent  2026-02-03 00:00:00
...            ...          ...        ...     ...                  ...
2035            12    Hyderabad     Retail   Agent  2021-07-10 00:00:00
2036             8       Mumbai  Corporate   Agent  2025-07-05 00:00:00
2037             8      Kolkata     Retail  Online  2022-10-17 00:00:00
2038             8    Bangalore     Retail   Agent  2023-08-26 00:00:00
2039             6      Chennai     Retail  Branch                  NaN

     Active Risk_Level Monthly_Spend Transactions  Satisfaction_Score
0       Yes        Low      23066.19          135                 3.1
1       Yes       High           NaN          106                 8.2
2        No     Medium      28536.34          146                 6.3
3       Yes       High      12869.71          115                 9.7
4        No       High      34163.02           94                 3.7
...     ...        ...           ...          ...                 ...
2035     No     Medium       8455.42          119                 8.6
2036    Yes       High      34087.69          134                 2.6
2037    Yes        Low      26518.74           87                 1.3
2038     No        Low      20943.11          107                 9.3
2039    Yes        Low      48511.32          119                 3.1

[2000 rows x 15 columns]
1.cleaning numeric column
 numeric column
      Customer_ID  Tenure_Years  Satisfaction_Score
0          101317             3                 3.1
1          101001             8                 8.2
2          101069            12                 6.3
3          101968            14                 9.7
4          100530             4                 3.7
...           ...           ...                 ...
2035       101131            12                 8.6
2036       101295             8                 2.6
2037       100861             8                 1.3
2038       101460             8                 9.3
2039       101127             6                 3.1

[2000 rows x 3 columns]
 finding missing value of each numeric columns
Customer_ID            0
Tenure_Years           0
Satisfaction_Score    80
dtype: int64
filling missing values with median
median of  Satisfaction_Score is 5.7
after cleaning dataset by  replacing median in missing value0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64
finding object column in  data
Index(['Age', 'Annual_Income', 'Account_Balance', 'Credit_Score', 'City',
       'Segment', 'Channel', 'Join_Date', 'Active', 'Risk_Level',
       'Monthly_Spend', 'Transactions'],
      dtype='object')
 suspecting  columns which contain invalid data
Age:
['55.0' '32.0' '23.0' '66.0' '67.0' '68.0' '47.0' '65.0' '63.0' '42.0'
 '25.0' '22.0' '52.0' '45.0' '27.0' '53.0' '64.0' '34.0' '40.0'
 'not_available' '70.0' '73.0' '18.0' '29.0' '46.0' '21.0' '57.0' '33.0'
 '51.0' '56.0' '31.0' '20.0' '44.0' '37.0' '38.0' '49.0' '62.0' nan '58.0'
 '75.0' '69.0' '74.0' '50.0' '35.0' '30.0' '24.0' '54.0' '60.0' '36.0'
 '59.0' '71.0' '19.0' '39.0' '43.0' '28.0' '26.0' '-' '72.0' 'missing'
 '41.0' '61.0' 'unknown' 'abc' '48.0']
Annual_Income:
['44033.0' '215546.0' '226403.0' ... '211994.0' '30105.0' '248332.0']
Account_Balance:
['111350.85' '254378.37' '159975.42' ... '160507.65' '32117.15'
 '274980.99']
Credit_Score:
['772' '374' '668' '315' '370' '738' '464' '554' '508' '556' '341' '477'
 '643' '542' '443' '693' '746' '314' '701' '725' '760' '311' '762' '397'
 '355' '597' '674' '747' '485' '487' '433' '503' '524' '429' '389' '805'
 '377' '820' '432' '829' '845' '661' '791' '639' '836' '452' '671' '360'
 '835' '456' '677' '478' '831' '481' '608' '682' '728' '688' '504' '510'
 '490' '560' '773' '710' '446' '422' '338' '534' '807' '713' '607' '357'
 '547' '617' '582' '822' '753' '672' '610' 'not_available' '398' '378'
 '444' '579' '437' '384' '598' '770' '536' '507' nan '566' '689' '421'
 '741' '794' '471' '712' 'missing' '667' '527' '745' '460' '516' '431'
 '650' '317' '599' '638' '588' '821' '751' '472' '328' '400' '596' '313'
 '606' '656' '681' '735' '465' '468' '691' '709' '553' '625' '511' '626'
 '707' '386' '601' '776' '658' '580' '525' '535' '614' '790' '634' '569'
 '461' '546' '577' '489' '827' '411' '497' '419' '368' '635' '633' '730'
 '367' '700' '832' '733' '715' '795' '306' '600' '837' '343' '325' '690'
 '742' '351' '797' '612' '312' '731' '752' '406' '453' '850' '573' '642'
 '714' '347' '561' '533' '445' '723' '704' '515' '724' '309' '782' '366'
 '574' '558' '592' '839' '396' '513' '528' '399' '603' '387' '448' '786'
 '686' '383' '316' '372' '514' '552' '463' '405' '318' '828' '414' '846'
 '349' '669' '499' '621' '454' '450' '509' '427' '675' '785' '390' '434'
 '320' '339' '467' '801' '519' '365' '623' '354' '813' '416' '564' '646'
 '567' '358' '819' '696' '393' '595' '348' '394' '766' '570' '439'
 'unknown' '302' '637' '652' '482' '792' '425' '413' '824' '754' '587'
 '657' '810' '727' '404' '605' '781' '609' '787' '763' '734' '834' '402'
 '483' '802' '736' '811' '721' '784' '530' '391' '655' '692' '783' '765'
 '767' '424' '520' '844' '630' '593' '572' '699' '326' '711' '743' '778'
 '344' '664' '581' '340' '447' '382' '480' '685' '645' '613' '687' '420'
 '375' '651' '708' '440' '529' '798' '550' '644' '492' '521' '800' '732'
 '473' '540' '842' '628' '624' '771' '632' '334' '518' '462' '673' '847'
 '739' '629' '526' '830' '457' 'abc' '337' '816' '342' '364' '840' '369'
 '474' '718' '476' '565' '545' '496' '523' '843' '833' '678' '-' '759'
 '307' '796' '611' '815' '361' '584' '808' '737' '345' '812' '575' '841'
 '300' '495' '591' '531' '616' '331' '818' '470' '352' '330' '705' '458'
 '549' '649' '576' '563' '505' '491' '849' '722' '479' '407' '415' '703'
 '670' '381' '604' '744' '538' '568' '401' '350' '825' '683' '466' '719'
 '641' '665' '449' '631' '555' '392' '329' '764' '373' '512' '740' '324'
 '327' '409' '653' '680' '308' '484' '498' '403' '438' '557' '640' '666'
 '380' '506' '590' '729' '777' '319' '814' '702' '356' '622' '430' '436'
 '660' '697' '548' '469' '823' '679' '848' '410' '571' '428' '838' '757'
 '758' '618' '544' '779' '301' '486' '488' '408' '517' '395' '455' '303'
 '799' '663' '559' '494' '418' '594' '817' '769' '793' '426' '788' '726'
 '475' '803' '750' '363' '493' '780' '636' '654' '768' '333' '500' '662'
 '537' '310' '748' '578' '620' '809' '583' '323' '417' '346' '532' '749'
 '385' '586' '332' '720' '806' '442' '647' '501' '551' '826' '706' '698'
 '695' '451' '412' '304' '627' '379' '619' '502' '761' '321' '648' '435'
 '353' '305' '676' '585' '756' '359' '335' '336' '602' '541' '371' '755'
 '362' '694' '804' '388']
City:
['Bangalore' 'Delhi' 'Chennai' 'Mumbai' ' bangalore ' 'Kolkata'
 'Hyderabad' nan 'Pune' ' chennai ' ' kolkata ' ' pune ' ' hyderabad '
 ' mumbai ' ' delhi ']
Segment:
['SME' 'Retail' 'Premium' 'Corporate' nan]
Channel:
['Agent' 'Online' 'Mobile' 'Branch']
Join_Date:
['2022-08-15 00:00:00' '2025-01-11 00:00:00' '2024-08-01 00:00:00' ...
 '2025-09-10 00:00:00' '2022-10-17 00:00:00' '2023-08-26 00:00:00']
Active:
['Yes' 'No' nan 'NO' '0' 'YES' 'Y' 'N' 'yes' '1' 'no']
Risk_Level:
['Low' 'High' 'Medium']
Monthly_Spend:
['23066.19' nan '28536.34' ... '26518.74' '20943.11' '48511.32']
Transactions:
['135' '106' '146' '115' '94' '6' '31' '139' '76' '124' '78' '56' '15'
 '66' '18' '110' '121' '95' '118' '43' '64' '128' '57' '132' '74' '75'
 '129' '45' '80' '14' '-' '16' '111' '7' '38' 'not_available' '98' '88'
 '148' '13' '85' '62' '103' '141' '84' '35' '17' '50' '112' '9' '59' '140'
 '63' '29' '72' '131' '108' '10' '23' '36' '22' '37' '102' '119' '147'
 '101' '24' '33' '48' '90' '20' '100' '86' '120' '40' '71' '136' '47'
 '144' '77' '109' '5' '19' '32' '123' '52' '3' '4' '149' '73' '39' '8'

Q30 — Ultimate Pandas Cleaning Project
You are a Data Scientist at a bank. Your raw customer dataset contains 2,000+ records with:

• Missing values
• Duplicate records
• Invalid numerical values
• Mixed datatypes
• Invalid dates
• Mixed date formats
• Inconsistent categorical values
• Binary text inconsistencies
• Unnecessary identifier columns
Your task is to produce a final clean analytical dataset.

Required workflow
Step 1 — Load
pd.read_csv()
Step 2 — Inspect
head()
tail()
sample()
info()

In [239]:
import pandas as pd
pd.read_csv(r"C:\Users\jyoti\Downloads\customer_analytics.csv")
print("dataset loaded successfully")
print(df.info())
print(df.sample())
print(df.head())
print(df.tail())
print("dataset inspected successfully")

dataset loaded successfully
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2000 non-null   int64
 1   age                 2000 non-null   float64
 2   anuual_income       1893 non-null   object
 3   account_balance     1875 non-null   object
 4   credit_score        2000 non-null   float64
 5   tenure_year         2000 non-null   int64
 6   city                1920 non-null   object
 7   segment             1900 non-null   object
 8   Channel             2000 non-null   object
 9   Join_Date           1875 non-null   datetime64[ns]
 10  Active              1942 non-null   object
 11  Risk_Level          2000 non-null   object
 12  Monthly_Spend       1893 non-null   object
 13  Transactions        2000 non-null   float64
 14  Satisfaction_Score  2000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(8)
memory usage: 250.0+ KB
None
      customer_id   age anuual_income account_balance  credit_score  \
1980       101843  69.0      179455.0       205387.86         448.0

      tenure_year   city  segment Channel  Join_Date Active Risk_Level  \
1980           13  Delhi  Premium  Online 2024-11-14     No       High

     Monthly_Spend  Transactions  Satisfaction_Score
1980      48460.63         125.0                 3.4
   customer_id   age anuual_income account_balance  credit_score  tenure_year  \
0       101317  55.0       44033.0       111350.85         772.0            3
1       101001  32.0      215546.0       254378.37         374.0            8
2       101069  23.0      226403.0       159975.42         668.0           12
3       101968  66.0       87824.0        295741.6         315.0           14
4       100530  67.0       31570.0       242423.78         370.0            4

          city  segment Channel  Join_Date Active Risk_Level Monthly_Spend  \
0    Bangalore      SME   Agent 2022-08-15    Yes        Low      23066.19
1        Delhi   Retail   Agent 2025-01-11    Yes       High           NaN
2      Chennai  Premium   Agent 2024-08-01     No     Medium      28536.34
3       Mumbai  Premium   Agent 2021-05-15    Yes       High      12869.71
4   bangalore    Retail   Agent 2026-02-03     No       High      34163.02

   Transactions  Satisfaction_Score
0         135.0                 3.1
1         106.0                 8.2
2         146.0                 6.3
3         115.0                 9.7
4          94.0                 3.7
      customer_id   age anuual_income account_balance  credit_score  \
2035       101131  42.0       88530.0       153490.72         677.0
2036       101295  31.0      205738.0        270989.4         392.0
2037       100861  25.0      211994.0       160507.65         737.0
2038       101460  64.0       30105.0        32117.15         794.0
2039       101127  55.0      248332.0       274980.99         783.0

      tenure_year       city    segment Channel  Join_Date Active Risk_Level  \
2035           12  Hyderabad     Retail   Agent 2021-07-10     No     Medium
2036            8     Mumbai  Corporate   Agent 2025-07-05    Yes       High
2037            8    Kolkata     Retail  Online 2022-10-17    Yes        Low
2038            8  Bangalore     Retail   Agent 2023-08-26     No        Low
2039            6    Chennai     Retail  Branch        NaT    Yes        Low

     Monthly_Spend  Transactions  Satisfaction_Score
2035       8455.42         119.0                 8.6
2036      34087.69         134.0                 2.6
2037      26518.74          87.0                 1.3
2038      20943.11         107.0                 9.3
2039      48511.32         119.0                 3.1
dataset inspected successfully

Step 3 — Missing-value analysis
isnull()
isna()

In [241]:
df.isnull()

,customer_id,age,anuual_income,account_balance,credit_score,tenure_year,city,segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2036,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2037,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2038,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2039,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

Step 4 — Duplicate handling
duplicated()
drop_duplicates()

In [244]:
print(df.duplicated())
df=df.drop_duplicates()
print(df)
print("duplicate handelled successfully")

0       False
1       False
2       False
3       False
4       False
        ...
2035    False
2036    False
2037    False
2038    False
2039    False
Length: 2000, dtype: bool
      customer_id   age anuual_income account_balance  credit_score  \
0          101317  55.0       44033.0       111350.85         772.0
1          101001  32.0      215546.0       254378.37         374.0
2          101069  23.0      226403.0       159975.42         668.0
3          101968  66.0       87824.0        295741.6         315.0
4          100530  67.0       31570.0       242423.78         370.0
...           ...   ...           ...             ...           ...
2035       101131  42.0       88530.0       153490.72         677.0
2036       101295  31.0      205738.0        270989.4         392.0
2037       100861  25.0      211994.0       160507.65         737.0
2038       101460  64.0       30105.0        32117.15         794.0
2039       101127  55.0      248332.0       274980.99         783.0

      tenure_year         city    segment Channel  Join_Date Active  \
0               3    Bangalore        SME   Agent 2022-08-15    Yes
1               8        Delhi     Retail   Agent 2025-01-11    Yes
2              12      Chennai    Premium   Agent 2024-08-01     No
3              14       Mumbai    Premium   Agent 2021-05-15    Yes
4               4   bangalore      Retail   Agent 2026-02-03     No
...           ...          ...        ...     ...        ...    ...
2035           12    Hyderabad     Retail   Agent 2021-07-10     No
2036            8       Mumbai  Corporate   Agent 2025-07-05    Yes
2037            8      Kolkata     Retail  Online 2022-10-17    Yes
2038            8    Bangalore     Retail   Agent 2023-08-26     No
2039            6      Chennai     Retail  Branch        NaT    Yes

     Risk_Level Monthly_Spend  Transactions  Satisfaction_Score
0           Low      23066.19         135.0                 3.1
1          High           NaN         106.0                 8.2
2        Medium      28536.34         146.0                 6.3
3          High      12869.71         115.0                 9.7
4          High      34163.02          94.0                 3.7
...         ...           ...           ...                 ...
2035     Medium       8455.42         119.0                 8.6
2036       High      34087.69         134.0                 2.6
2037        Low      26518.74          87.0                 1.3
2038        Low      20943.11         107.0                 9.3
2039        Low      48511.32         119.0                 3.1

[2000 rows x 15 columns]

In [ ]:
Step 5 — Numeric cleaning
Clean:
age
Annual_Income
Account_Balance
Credit_Score
Monthly_Spend
Transactions
Satisfaction_Score

In [250]:
print(" to clean the  column first we need to convert the numeric values to proper numeric data type and invalid values in column to missing values")
df["age"]=pd.to_numeric(df["age"],errors="coerce")
df["anuual_income"]=pd.to_numeric(df["anuual_income"],errors="coerce")
df["credit_score"]=pd.to_numeric(df["credit_score"],errors="coerce")
df["Monthly_Spend "]=pd.to_numeric(df["Monthly_Spend"],errors="coerce")
df["Transactions"]=pd.to_numeric(df["Transactions"],errors="coerce")
df["Satisfaction_Score"]=pd.to_numeric(df["Satisfaction_Score"],errors="coerce")
print(df["age"])
print(df["anuual_income"])
print(df["credit_score"])
print(df["Monthly_Spend"])
print(df["Transactions"])
print(df["Satisfaction_Score"])
print("as there is no missing values found so no need to fill them")

 to clean the  column first we need to convert the numeric values to proper numeric data type and invalid values in column to missing values
0       55.0
1       32.0
2       23.0
3       66.0
4       67.0
        ...
2035    42.0
2036    31.0
2037    25.0
2038    64.0
2039    55.0
Name: age, Length: 2000, dtype: float64
0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: anuual_income, Length: 2000, dtype: float64
0       772.0
1       374.0
2       668.0
3       315.0
4       370.0
        ...
2035    677.0
2036    392.0
2037    737.0
2038    794.0
2039    783.0
Name: credit_score, Length: 2000, dtype: float64
0       23066.19
1            NaN
2       28536.34
3       12869.71
4       34163.02
          ...
2035     8455.42
2036    34087.69
2037    26518.74
2038    20943.11
2039    48511.32
Name: Monthly_Spend, Length: 2000, dtype: object
0       135.0
1       106.0
2       146.0
3       115.0
4        94.0
        ...
2035    119.0
2036    134.0
2037     87.0
2038    107.0
2039    119.0
Name: Transactions, Length: 2000, dtype: float64
0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64

In [ ]:
Step 6 — Date cleaning
Clean:
Join_Date
using:
pd.to_datetime()

In [256]:
df["Join_Date"]=pd.to_datetime(df["Join_Date"],errors="coerce")
print(df["Join_Date"])
df["Join_Date"]=df["Join_Date"].ffill()# missing values is filled by its previos values using forward fill method
print(df["Join_Date"])

0      2022-08-15 00:00:00.000
1      2025-01-11 00:00:00.000
2      2024-08-01 00:00:00.000
3      2021-05-15 00:00:00.000
4      2026-02-03 00:00:00.000
                 ...
2035   2021-07-10 00:00:00.000
2036   2025-07-05 00:00:00.000
2037   2022-10-17 00:00:00.000
2038   2023-08-26 00:00:00.000
2039   2023-08-23 23:13:55.200
Name: Join_Date, Length: 2000, dtype: datetime64[ns]
 mean of this column is:
2023-08-23 23:13:55.200000
 filling the missng values with mean
0      2022-08-15 00:00:00.000
1      2025-01-11 00:00:00.000
2      2024-08-01 00:00:00.000
3      2021-05-15 00:00:00.000
4      2026-02-03 00:00:00.000
                 ...
2035   2021-07-10 00:00:00.000
2036   2025-07-05 00:00:00.000
2037   2022-10-17 00:00:00.000
2038   2023-08-26 00:00:00.000
2039   2023-08-23 23:13:55.200
Name: Join_Date, Length: 2000, dtype: datetime64[ns]

In [ ]:
Step 7 — Categorical cleaning
Clean:
City
Segment
Channel
Active
Risk_Level
replace()
value_counts()
fillna()

In [266]:
print(" distribution of  values of each column,; 'City','Segment','Channel','Active','Risk_Level'")
print(df["segment"].value_counts())
print(df["Channel"].value_counts())
print(df["Active"].value_counts())
print(df["City"].value_counts())
print(df["Risk_Level"].value_counts())
print(' as every column have unique values except"Active" we only need to clean this or standardise this')
df["Active"]=df["Active"].replace({"Y":"YES","N":"NO",1:"YES",0:"NO","no":"NO","yes":"YES"})
print(df["Active"])
print("finding missing values in this column")
print(df["Active"].isnull().sum())
print("filling missing values")
df["Active"]=df["Active"].ffill()
print(df["Active"])

 distribution of  values of each column,; 'City','Segment','Channel','Active','Risk_Level'
segment
Premium      516
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64
Channel
Agent     530
Online    497
Branch    493
Mobile    480
Name: count, dtype: int64
Active
Yes    1288
No      534
NO       47
YES      45
0        16
1        12
Name: count, dtype: int64
Channel
Agent     530
Online    497
Branch    493
Mobile    480
Name: count, dtype: int64
Risk_Level
High      986
Low       540
Medium    474
Name: count, dtype: int64
 as every column have unique values except"Active" we only need to clean this or standardise this
0       Yes
1       Yes
2        No
3       Yes
4        No
       ...
2035     No
2036    Yes
2037    Yes
2038     No
2039    Yes
Name: Active, Length: 2000, dtype: object
finding missing values in this column
58
filling missing values
0       Yes
1       Yes
2        No
3       Yes
4        No
       ...
2035     No
2036    Yes
2037    Yes
2038     No
2039    Yes
Name: Active, Length: 2000, dtype: object

In [ ]:
Step 9 — Create analytical features
Create at least these:
Income_Lakhs
MonthlyIncome
Income_After_Spending
Balance_Income_Ratio

TypeError: unsupported operand type(s) for /: 'str' and 'float'

Step 10 — Final validation
Your final DataFrame must pass these checks:
No duplicate rows
No invalid numeric values
No unexpected object datatype in numeric columns
No invalid dates
No inconsistent Yes/No values

Missing values handled
Column names standardized

Finally display:
head()
tail()
sample()
info()
describe()
value_counts()

In [274]:
print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.describe())
print(df.value_counts())

   customer_id   age  anuual_income account_balance  credit_score  \
0       101317  55.0        44033.0       111350.85         772.0
1       101001  32.0       215546.0       254378.37         374.0
2       101069  23.0       226403.0       159975.42         668.0
3       101968  66.0        87824.0        295741.6         315.0
4       100530  67.0        31570.0       242423.78         370.0

   tenure_year         city  segment Channel  Join_Date Active Risk_Level  \
0            3    Bangalore      SME   Agent 2022-08-15    Yes        Low
1            8        Delhi   Retail   Agent 2025-01-11    Yes       High
2           12      Chennai  Premium   Agent 2024-08-01     No     Medium
3           14       Mumbai  Premium   Agent 2021-05-15    Yes       High
4            4   bangalore    Retail   Agent 2026-02-03     No       High

  Monthly_Spend  Transactions  Satisfaction_Score  Monthly_Spend   \
0      23066.19         135.0                 3.1        23066.19
1           NaN         106.0                 8.2             NaN
2      28536.34         146.0                 6.3        28536.34
3      12869.71         115.0                 9.7        12869.71
4      34163.02          94.0                 3.7        34163.02

   Income_Lakhs  MonthlyIncome
0       0.44033    3669.416667
1       2.15546   17962.166667
2       2.26403   18866.916667
3       0.87824    7318.666667
4       0.31570    2630.833333
      customer_id   age  anuual_income account_balance  credit_score  \
2035       101131  42.0        88530.0       153490.72         677.0
2036       101295  31.0       205738.0        270989.4         392.0
2037       100861  25.0       211994.0       160507.65         737.0
2038       101460  64.0        30105.0        32117.15         794.0
2039       101127  55.0       248332.0       274980.99         783.0

      tenure_year       city    segment Channel               Join_Date  \
2035           12  Hyderabad     Retail   Agent 2021-07-10 00:00:00.000
2036            8     Mumbai  Corporate   Agent 2025-07-05 00:00:00.000
2037            8    Kolkata     Retail  Online 2022-10-17 00:00:00.000
2038            8  Bangalore     Retail   Agent 2023-08-26 00:00:00.000
2039            6    Chennai     Retail  Branch 2023-08-23 23:13:55.200

     Active Risk_Level Monthly_Spend  Transactions  Satisfaction_Score  \
2035     No     Medium       8455.42         119.0                 8.6
2036    Yes       High      34087.69         134.0                 2.6
2037    Yes        Low      26518.74          87.0                 1.3
2038     No        Low      20943.11         107.0                 9.3
2039    Yes        Low      48511.32         119.0                 3.1

      Monthly_Spend   Income_Lakhs  MonthlyIncome
2035         8455.42       0.88530    7377.500000
2036        34087.69       2.05738   17144.833333
2037        26518.74       2.11994   17666.166667
2038        20943.11       0.30105    2508.750000
2039        48511.32       2.48332   20694.333333
     customer_id   age  anuual_income account_balance  credit_score  \
781       101671  75.0       156354.0       234484.64         401.0

     tenure_year       city segment Channel  Join_Date Active Risk_Level  \
781           13  Hyderabad     NaN  Branch 2022-08-28    Yes       High

    Monthly_Spend  Transactions  Satisfaction_Score  Monthly_Spend   \
781       2866.65           6.0                 5.7         2866.65

     Income_Lakhs  MonthlyIncome
781       1.56354        13029.5
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         2000 non-null   int64
 1   age                 2000 non-null   float64
 2   anuual_income       1851 non-null   float64
 3   account_balance     1875 non-null   object
 4   credit_score        2000 non-null   float64
 5   tenure_year         2000 non-null   int64
 6   city                1920 non-null   object
 7   segment             1900 non-null   object
 8   Channel             2000 non-null   object
 9   Join_Date           2000 non-null   datetime64[ns]
 10  Active              2000 non-null   object
 11  Risk_Level          2000 non-null   object
 12  Monthly_Spend       1893 non-null   object
 13  Transactions        2000 non-null   float64
 14  Satisfaction_Score  2000 non-null   float64
 15  Monthly_Spend       1854 non-null   float64
 16  Income_Lakhs        1851 non-null   float64
 17  MonthlyIncome       1851 non-null   float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(7)
memory usage: 296.9+ KB
None
         customer_id          age  anuual_income  credit_score  tenure_year  \
count    2000.000000  2000.000000    1851.000000   2000.000000  2000.000000
mean   101000.500000    47.006000  138237.069692    576.251500     7.574000
min    100001.000000    18.000000   25163.000000    300.000000     0.000000
25%    100500.750000    34.000000   82789.500000    434.000000     4.000000
50%    101000.500000    47.000000  139914.000000    570.500000     8.000000
75%    101500.250000    61.000000  192738.500000    720.250000    12.000000
max    102000.000000    75.000000  249977.000000    850.000000    15.000000
std       577.494589    16.184991   64427.636380    160.930148     4.610548

                        Join_Date  Transactions  Satisfaction_Score  \
count                        2000    2000.00000         2000.000000
mean   2023-08-23 23:13:55.200000      75.46050            5.609200
min           2021-01-01 00:00:00       1.00000            1.000000
25%           2022-06-10 12:00:00      40.00000            3.600000
50%    2023-08-23 23:13:55.200000      76.00000            5.700000
75%           2024-11-05 00:00:00     112.00000            7.700000
max           2026-03-13 00:00:00     149.00000           10.000000
std                           NaN      42.57714            2.527554

       Monthly_Spend   Income_Lakhs  MonthlyIncome
count     1854.000000   1851.000000    1851.000000
mean     24863.615345      1.382371   11519.755808
min        559.580000      0.251630    2096.916667
25%      12180.207500      0.827895    6899.125000
50%      24625.170000      1.399140   11659.500000
75%      37511.300000      1.927385   16061.541667
max      49942.820000      2.499770   20831.416667
std      14385.791547      0.644276    5368.969698
customer_id  age   anuual_income  account_balance  credit_score  tenure_year  city       segment    Channel  Join_Date   Active  Risk_Level  Monthly_Spend  Transactions  Satisfaction_Score  Monthly_Spend   Income_Lakhs  MonthlyIncome
100003       46.0  108560.0       249995.12        712.0         3            Delhi      SME        Mobile   2021-02-21  Yes     Low         26986.15       120.0         5.6                 26986.15        1.08560       9046.666667      1
101336       23.0  107617.0       112959.09        743.0         9            Pune       Retail     Mobile   2022-10-23  Yes     Low         47236.63       42.0          2.5                 47236.63        1.07617       8968.083333      1
101334       68.0  37087.0        180084.44        738.0         1            Chennai    Premium    Agent    2023-06-04  Yes     Low         15121.16       6.0           8.5                 15121.16        0.37087       3090.583333      1
101333       56.0  210413.0       187043.35        406.0         14           Kolkata    Premium    Online   2025-12-27  Yes     High        38452.23       36.0          1.8                 38452.23        2.10413       17534.416667     1
101332       68.0  30110.0        225502.85        666.0         12           Pune       Retail     Agent    2021-03-23  No      Medium      10611.11       143.0         1.6                 10611.11        0.30110       2509.166667      1
                                                                                                                                                                                                                                            ..
100652       40.0  167635.0       234219.56        396.0         8            Hyderabad  Retail     Mobile   2022-11-10  No      High        2429.13        68.0          4.8                 2429.13         1.67635       13969.583333     1
100651       52.0  183670.0       168027.51        508.0         6            Kolkata    Corporate  Branch   2024-01-04  Yes     High        13938.47       115.0         8.3                 13938.47        1.83670       15305.833333     1
100649       68.0  78551.0        189647.85        525.0         3            Pune       Retail     Branch   2024-10-23  Yes     High        1042.81        16.0          9.6                 1042.81         0.78551       6545.916667      1
100648       19.0  106889.0       284762.59        389.0         10           Pune       SME        Branch   2023-03-30  Yes     High        44420.9        28.0          1.4                 44420.90        1.06889       8907.416667      1
102000       31.0  79245.0        44508.1          324.0         6            Bangalore  Premium    Online   2025-12-24  Yes     High        5314.08        16.0          1.4                 5314.08         0.79245       6603.750000      1
Name: count, Length: 1457, dtype: int64