**1.Load the CSV using Pandas and display the first 10 rows.**

In [5]:
import pandas as pd
print(" DATASET LOADED SUCCESSFULLY:")
print("*"*90)
df=pd.read_csv("C:\\Users\\jyoti\\Downloads\\customer_data - customer_data.csv")
print(df)
print("*"*90)
print("FIRST 10 ROWS:")
print(df.head(10))

 DATASET LOADED SUCCESSFULLY:
******************************************************************************************
     Customer ID          Age   income_usd credit Score  tenure_years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      monthly_visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune         consumer    NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  2026-03-11    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  2024-09-20       Email               NaN
3            N         No  2023-07-12     Website            normal
4          Yes         No  2024-08-06         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  2024-02-26       email            normal
1996         N        Yes  2024-08-11     Website              good
1997       yes         No  2023-05-27         WEB               ???
1998         N        Yes  2025-01-26       Email                ok
1999       yes         No  2024-02-22         ???              good

[2000 rows x 15 columns]
******************************************************************************************
FIRST 10 ROWS:
  Customer ID          Age   income_usd credit Score  tenure_years  \
0  CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1  CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2  CUST-01334          NaN  44199.67124  613.1327754           NaN
3  CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4  CUST-01290          NaN  31238.64196  549.1832523      2.648626
5  CUST-01274          NaN      $44,696          NaN      1.700044
6  CUST-00939  49.28347358  44108.07925  793.2135773     10.077820
7  CUST-01732  37.63000983  80888.86264          850      4.489813
8  CUST-00066  47.52016682  50011.55556   796.794099      9.074520
9  CUST-01324          NaN  84410.30824  482.3950729      6.820629

   monthly_visits  satisfaction       City customer_segment  gender is_active  \
0             5.0      3.382150       Pune         consumer     NaN       Yes
1             9.0           NaN  Hyderabad         Consumer    Male       NaN
2             8.0      4.195157     Mumbai         Consumer       m       Yes
3             4.0           NaN    Chennai       Enterprise       m         N
4             5.0      3.117326     Mumbai       Enterprise    Male       Yes
5            12.0           NaN  Bengaluru              SMB    Male       Yes
6             7.0      3.872187    Kolkata         Consumer     NaN       yes
7            11.0           NaN       Pune              NaN  Female         N
8             4.0      3.694925       Pune             SMB.       m        No
9             3.0      2.636945     Mumbai         Consumer       M        no

  churn_flag signup_date lead_source        notes_text
0         No  2026-03-11    Referral               NaN
1         No         NaN     website  follow-up needed
2         No  2024-09-20       Email               NaN
3         No  2023-07-12     Website            normal
4         No  2024-08-06         NaN               ???
5        Yes  21/07/2024         NaN  follow-up needed
6        Yes  2023-08-14  google_ads               NaN
7         No         NaN         NaN     good customer
8        NaN  2021-03-08      Social               NaN
9         No  2024-09-10     Website            normal

**2.Check the number of rows and columns in the dataset.**

In [10]:
print("NUMBER OF COLUMNS AND ROWS IN DATASET:")
df.shape

NUMBER OF COLUMNS AND ROWS IN DATASET

(2000, 15)

**3. Display all column names and identify which column names contain
leading/trailing spaces or inconsistent capitalization.**

In [26]:
print(" DISPLAYING ALL COLUMN NAMES:")
print(df.columns.tolist())
print("identifying which column names containleading/trailing spaces or inconsistent capitalization")
for col in df.columns.tolist():
    

  if col!=col.strip():
        print(repr(col))
for col in df.columns.tolist():
        if col!=col.lower():
            
            print(col)

 DISPLAYING ALL COLUMN NAMES:
['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years', 'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender', 'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text']
identifying which column names containleading/trailing spaces or inconsistent capitalization
Customer ID
Age
credit Score
City

**4.Check the data type of every column using Pandas.**

In [37]:
 for col in df.columns.tolist():
     print(f"DATATYPE OF '{col}':- {df[col].dtypes}")
     print("*"*100)

DATATYPE OF 'Customer ID':- object
****************************************************************************************************
DATATYPE OF 'Age':- object
****************************************************************************************************
DATATYPE OF 'income_usd':- object
****************************************************************************************************
DATATYPE OF 'credit Score':- object
****************************************************************************************************
DATATYPE OF 'tenure_years':- float64
****************************************************************************************************
DATATYPE OF 'monthly_visits':- float64
****************************************************************************************************
DATATYPE OF 'satisfaction':- float64
****************************************************************************************************
DATATYPE OF 'City':- object
****************************************************************************************************
DATATYPE OF 'customer_segment':- object
****************************************************************************************************
DATATYPE OF 'gender':- object
****************************************************************************************************
DATATYPE OF 'is_active':- object
****************************************************************************************************
DATATYPE OF 'churn_flag':- object
****************************************************************************************************
DATATYPE OF 'signup_date':- object
****************************************************************************************************
DATATYPE OF 'lead_source':- object
****************************************************************************************************
DATATYPE OF 'notes_text':- object
****************************************************************************************************

**5.Calculate the number and percentage of missing values in every column.**

In [51]:
for col in df.columns:
    print(f"MISSING VALUE IN COLUMN'{col}':{df[col].isna().sum()}")
    print("*"*100)
print("\nPERCENTAGE OF MISSING VALUES IN EVERY COLUMNS:")
print((df.isnull().sum()/len(df))*100)

MISSING VALUE IN COLUMN'Customer ID':20
****************************************************************************************************
MISSING VALUE IN COLUMN'Age':331
****************************************************************************************************
MISSING VALUE IN COLUMN'income_usd':440
****************************************************************************************************
MISSING VALUE IN COLUMN'credit Score':360
****************************************************************************************************
MISSING VALUE IN COLUMN'tenure_years':258
****************************************************************************************************
MISSING VALUE IN COLUMN'monthly_visits':280
****************************************************************************************************
MISSING VALUE IN COLUMN'satisfaction':399
****************************************************************************************************
MISSING VALUE IN COLUMN'City':300
****************************************************************************************************
MISSING VALUE IN COLUMN'customer_segment':380
****************************************************************************************************
MISSING VALUE IN COLUMN'gender':240
****************************************************************************************************
MISSING VALUE IN COLUMN'is_active':340
****************************************************************************************************
MISSING VALUE IN COLUMN'churn_flag':160
****************************************************************************************************
MISSING VALUE IN COLUMN'signup_date':240
****************************************************************************************************
MISSING VALUE IN COLUMN'lead_source':420
****************************************************************************************************
MISSING VALUE IN COLUMN'notes_text':656
****************************************************************************************************

PERCENTAGE OF MISSING VALUES IN EVERY COLUMNS:
Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

**6.Find the rows where Customer ID is missing.**

In [58]:
print("rows where Customer ID is missing:")
df.loc[df["Customer ID"].isnull()]

rows where Customer ID is missing

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

**7. Remove leading/trailing whitespace from all column names and convert them
to lowercase with underscores.**

In [61]:
df.columns.str.strip().str.lower().str.replace(" ","-")

Index(['customer-id', 'age', 'income_usd', 'credit-score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

**8.Identify duplicate Customer ID values and count how many duplicates exist.**

In [66]:
print("DUPLICATE CUSTOMER ID VALUES:")
print(df[df["Customer ID"].duplicated()])
print("NO OF DUPLICATE VALUES:")
print(df["Customer ID"].duplicated().sum())

DUPLICATE CUSTOMER ID VALUES:
     Customer ID          Age   income_usd credit Score  tenure_years  \
226          NaN           18  58188.80528  737.9284458     15.655950
300          NaN          NaN  93665.74378  703.9692987     12.723292
421          NaN   29.6 years          NaN  641.3441152      8.940646
770          NaN  20.39545706  92366.06753  767.8048841      4.524943
821          NaN  46.41996378  81119.71831  597.3307848      1.076200
876          NaN  36.57634009  76629.87047   699.109735      4.977078
993          NaN  47.54933612          NaN          NaN      0.693710
1023         NaN          NaN  34219.41505          NaN      3.779121
1188         NaN  28.97406958          NaN      744 pts      7.947965
1202         NaN  42.23152645  35310.77625  684.8618643      2.465432
1212         NaN  56.44358785      $99,697  749.3298384      3.743193
1248         NaN  34.60645101  96811.19575  798.1150352      1.551247
1338         NaN   26.5 years      $89,682  692.0794813      1.877392
1346         NaN  46.22898842  60122.78196  684.8548451      3.837557
1448         NaN           18          NaN   628.337014      7.137356
1451         NaN  47.20187446  28270.08329  549.3662455      3.019237
1462         NaN  49.99203599  58348.28529  511.5806801      2.775352
1564         NaN  42.96550781      $64,045      561 pts      4.549291
1652         NaN  33.27510593  37475.10034          NaN      4.345689

      monthly_visits  satisfaction       City customer_segment  gender  \
226             12.0      3.330254    Chennai         Consumer  Female
300              7.0           NaN       Pune              SMB  Female
421              5.0      3.687539        NaN         Consumer  Female
770              3.0      4.358065     Mumbai       Enterprise       f
821              5.0      4.346306      Delhi         consumer       f
876              6.0      2.700057     Mumbai         consumer       M
993              4.0      3.659781        NaN       Enterprise     NaN
1023             4.0      3.529211  Hyderabad              NaN       M
1188             8.0      2.379383  Hyderabad         Consumer       f
1202             6.0      4.979391      Delhi              SMB       m
1212             6.0           NaN        NaN              NaN       M
1248             5.0      3.288656     Mumbai             SMB.       M
1338             4.0      3.783551       Pune         Consumer       m
1346             2.0      4.267750     Mumbai         consumer       F
1448             5.0           NaN       Pune       Enterprise  Female
1451             6.0      3.441021  Hyderabad              SMB       m
1462             NaN           NaN     Mumbai              SMB  Female
1564             4.0      3.513904    Chennai         Consumer       m
1652            11.0   -999.000000     Mumbai              SMB       f

     is_active churn_flag signup_date lead_source        notes_text
226          Y        NaN  2022-03-18    Referral            normal
300          1         No         NaN       Email  follow-up needed
421          1         No  2021-12-05     Unknown               NaN
770          N         No  2021-09-05         ???               NaN
821          1        Yes  2022-12-26       Email               NaN
876          N        Yes  2021-07-01    referral              good
993        NaN         No  2024-07-09    Referral      late payment
1023         N         No  2023-07-05  Google Ads                ok
1188       Yes         No  2026-06-06         NaN            urgent
1202         1         No  2024-10-10  google_ads      late payment
1212         Y        Yes  2024-07-18         WEB               NaN
1248         N         No  2023-09-16      Social  follow-up needed
1338         N         No  2023-12-04         WEB               NaN
1346         N        Yes  2023-01-01    referral  follow-up needed
1448        no        NaN  2024-08-25  Google Ads               NaN
1451       yes        Yes  2023-10-12     Unknown              good
1462        no         No  2024-07-07         NaN               NaN
1564        No         No  03/08/2023       Email               NaN
1652       NaN        NaN  2022-02-15      Social                ok
NO OF DUPLICATE VALUES:
19

**Remove duplicate customer records while keeping the first occurrence.**

In [70]:
df.drop_duplicates(subset=["Customer ID"],keep="first")

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

**10.Find all unique values in the customer_segment column and identify
inconsistent categories such as Consumer, consumer, consumer , etc.**

In [86]:
print("Unique customer segments:")
print(df["customer_segment"].unique())

print("\nInconsistent categories:")

for values in df["customer_segment"].unique():
    if pd.notna(values):
        if values != values.lower().strip():
            print(repr(values))

Unique customer segments:
['consumer' 'Consumer' 'Enterprise' 'SMB' nan 'SMB.' 'UNKNOWN']

Inconsistent categories:
'Consumer'
'Enterprise'
'SMB'
'SMB.'
'UNKNOWN'

**11.Clean the customer_segment column by standardizing capitalization and
whitespace.**

In [88]:
df["customer_segment"]=df["customer_segment"].str.strip().str.lower()
print(df["customer_segment"])

0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 2000, dtype: object

**12.Find all unique values in the gender column and convert them into consistent
categories such as Male and Female.**

In [95]:
print("UNIQUE VALUES IN 'gender'  COLUMN:")
print(df["gender"].unique())
df["gender"]=df["gender"].replace({"m":"Male","f":"Female","F":"Female","M":"Male"})
print(f'\n after converting  them into consistentcategories such as Male and Female :{df["gender"]}')

UNIQUE VALUES IN 'gender'  COLUMN:
[nan 'Male' 'Female']

 after converting  them into consistentcategories such as Male and Female :0          NaN
1         Male
2         Male
3         Male
4         Male
         ...
1995      Male
1996      Male
1997    Female
1998       NaN
1999       NaN
Name: gender, Length: 2000, dtype: object

**13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
No, no, N, 0 become 0.**

In [102]:
print('unique values of  column"is_active" is :')
print(df["is_active"].unique().tolist())
print("\nafter cleaning such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0 :")
df["is_active"]=df["is_active"].replace({"Yes":1,"yes":1,"Y":1,"No":0,"N":0,"no":0})
print(df["is_active"].value_counts())

unique values of  column"is_active" is :
[1, nan, 0, '1', '0']

after cleaning such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0 :
is_active
1    625
0    625
1    224
0    186
Name: count, dtype: int64

**14.Convert the churn_flag column from categorical values (Yes/No) into a binary
numerical column (1/0).**

In [109]:
print(df["churn_flag"].unique())
print("column from categorical values (Yes/No) into a binarynumerical column (1/0)")
df["churn_flag"]=df["churn_flag"].replace({"No":0,"Yes":1})
print(df["churn_flag"])

['No' 'Yes' nan]
column from categorical values (Yes/No) into a binarynumerical column (1/0)
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag, Length: 2000, dtype: float64

C:\Users\jyoti\AppData\Local\Temp\ipykernel_28940\3044684980.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["churn_flag"]=df["churn_flag"].replace({"No":0,"Yes":1})

**15.Identify all values in income_usd that cannot be directly interpreted as
numbers.**

5      NaN
10     NaN
11     NaN
13     NaN
18     NaN
        ..
1980   NaN
1985   NaN
1989   NaN
1990   NaN
1991   NaN
Name: income_usd, Length: 645, dtype: float64

**16.Clean income_usd by removing currency symbols, commas, and invalid text,
then convert it to a numeric column using pd.to_numeric().**

In [124]:
df["income_usd"]=df["income_usd"].astype("str")
df["income_usd"] = df["income_usd"].str.replace("$", "", regex=False)
df["income_usd"] = df["income_usd"].str.replace(",", "", regex=False)

df["income_usd"] = pd.to_numeric(
    df["income_usd"],
    errors="coerce"
)

print(df["income_usd"])

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: float64

**17.Clean the Age column so values such as "35 years" become numeric values.**

In [137]:
df["Age"]=df["Age"].astype("str")
df["Age"]=df["Age"].str.replace("years","")
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
print(df["Age"])

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: Age, Length: 2000, dtype: float64

**18.Identify unrealistic age values using NumPy/Pandas and replace them with
NaN.**

In [148]:
import numpy as np
Q1=df["Age"].quantile(0.25)
Q3=df["Age"].quantile(0.75)
IQR=Q3-Q1
lower_limit=Q1-(IQR*1.5)
upper_limit=Q3+(IQR*1.5)
df.loc[(df["Age"]<lower_limit)|(df["Age"]>upper_limit),"Age"]=np.nan
print(df["Age"])

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: Age, Length: 2000, dtype: float64

**OR**

In [151]:
import numpy as np
df.loc[(df["Age"]<0)|(df["Age"]>100),"Age"]=np.nan
print(df["Age"])

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: Age, Length: 2000, dtype: float64

In [ ]:
**19.Clean the credit Score column by removing text such as "pts" and converting
the column to numeric.**

In [164]:
print("ALL VALUES OF COLUMN 'credit score':")
print("*"*50)
print(df["credit Score"].unique())
print("\n CLEAN 'credit score' COLUMN AFTER REMOVING TEXT SUCH AS 'pts':")
df["credit Score"]=df["credit Score"].astype("str")
df["credit Score"]=df["credit Score"].str.replace("pts","")
print(df["credit Score"])
print("AFTER CONVERTING THE COLUMN TO NUMERIC")
df["credit Score"]=pd.to_numeric(df["credit Score"],errors="coerce")
print(df["credit Score"])

ALL VALUES OF COLUMN 'credit score':
**************************************************
['660.5629176' '838 ' '613.1327754' ... '701.7201056' '647.7993363'
 '576.7390735']

 CLEAN 'credit score' COLUMN AFTER REMOVING TEXT SUCH AS 'pts':
0       660.5629176
1              838
2       613.1327754
3       720.2369862
4       549.1832523
           ...
1995    633.9740063
1996    701.7201056
1997    647.7993363
1998           521
1999    576.7390735
Name: credit Score, Length: 2000, dtype: object
AFTER CONVERTING THE COLUMN TO NUMERIC
0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit Score, Length: 2000, dtype: float64

**20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.**

In [166]:
#using pandas  
Q1=df["income_usd"].quantile(0.25)
Q3=df["income_usd"].quantile(0.75)
IQR=Q3-Q1
lower_limit=Q1-(IQR*1.5)
upper_limit=Q3+(IQR*1.5)
print("OUTLIER IN COLUMN  income_usd:")
OUTLIER=df.loc[(df["income_usd"]<lower_limit)|(df["income_usd"]<lower_limit),"income_usd"]

print(OUTLIER)

OUTLIER IN COLUMN  income_usd:
Series([], Name: income_usd, dtype: float64)

In [ ]:
#using numpy

**21.Detect outliers in credit Score using the IQR method.**

In [169]:
Q1=df["credit Score"].quantile(0.25)
Q3=df["credit Score"].quantile(0.75)
IQR=Q3-Q1
lower_limit=Q1-IQR*1.5
upper_limit=Q3+IQR*1.5
outlier=df.loc[(df["credit Score"]<lower_limit)|(df["credit Score"]>upper_limit),"credit Score"]
print(f"outliers in 'credit Score' is:{outlier}")

outliers in 'credit Score' is:62      404.916112
348     395.344523
377     372.537221
422     162.336676
425     181.226519
446     141.922798
664     252.000000
705     218.521526
734     362.424198
793     211.984092
877     215.344839
904     389.270475
922     406.124323
942     240.729898
1024    195.707600
1027    151.039790
1102    216.621015
1194    225.420626
1263    393.470830
1425    356.305997
1516    280.213170
1613    248.101304
1630    261.433939
1665    179.409088
1830    332.371104
Name: credit Score, dtype: float64

**22.Detect suspicious values such as -999 and 99999 in tenure_years and
satisfaction.**

In [314]:
print(' TOTAL  UNIQUE VALUES IN COLUMN "tenure_years" IS :')
print(df["tenure_years"].unique())
for value in df["tenure_years"].unique():
    if value==-999&99999:
        print(f"suspicious values  {value} detected in column 'tenure_years'")
    
for value in df["satisfaction"]:
    if value==-999&99999:
        print(f"suspicious values  {value} detected in column 'satisfaction'")

 TOTAL  UNIQUE VALUES IN COLUMN "tenure_years" IS :
[5.27407587 5.63282603 4.68877724 ... 2.02648455 7.1681559  9.72066303]
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found
no suspicious value found

**23.Replace invalid/suspicious numerical values with NaN.**

In [176]:
print("NUMERICAL COLUMNS:")
print("-"*100)
print(df.select_dtypes(["number"]).columns)
for col in  df.select_dtypes(["number"]).columns:
    print(f"AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN '{col}' with nan:")
    df[col]=pd.to_numeric(df[col],errors="coerce")
    print(df[col])

NUMERICAL COLUMNS:
----------------------------------------------------------------------------------------------------
Index(['Age', 'income_usd', 'credit Score', 'tenure_years', 'monthly_visits',
       'satisfaction', 'churn_flag'],
      dtype='object')
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN Age with nan:
0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: Age, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN income_usd with nan:
0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN credit Score with nan:
0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit Score, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN tenure_years with nan:
0        5.274076
1        5.632826
2             NaN
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN monthly_visits with nan:
0        5.0
1        9.0
2        8.0
3        4.0
4        5.0
        ...
1995     NaN
1996     8.0
1997    12.0
1998     5.0
1999     NaN
Name: monthly_visits, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN satisfaction with nan:
0       3.382150
1            NaN
2       4.195157
3            NaN
4       3.117326
          ...
1995    3.556073
1996    2.963094
1997    3.079259
1998    3.579652
1999    1.100520
Name: satisfaction, Length: 2000, dtype: float64
AFTER REPLACING INVALID SUSPICIOUS NUMERICAL VALUES OF COLUMN churn_flag with nan:
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag, Length: 2000, dtype: float64

**24.Fill missing numerical values using the median of each numerical column.**

In [188]:
num_column = df.select_dtypes(["number"]).columns

for col in num_column:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)
    
    print(f"{col}: Missing values filled with median = {median_value}")
    print(f"after filling '{col}':{df[col]}")

Age: Missing values filled with median = 37.85498419
after filling 'Age':0       45.867417
1       47.765164
2       37.854984
3       62.723578
4       37.854984
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: Age, Length: 2000, dtype: float64
income_usd: Missing values filled with median = 56584.86961
after filling 'income_usd':0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: float64
credit Score: Missing values filled with median = 647.91439
after filling 'credit Score':0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit Score, Length: 2000, dtype: float64
tenure_years: Missing values filled with median = 4.688777237
after filling 'tenure_years':0        5.274076
1        5.632826
2        4.688777
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 2000, dtype: float64
monthly_visits: Missing values filled with median = 6.0
after filling 'monthly_visits':0        5.0
1        9.0
2        8.0
3        4.0
4        5.0
        ...
1995     6.0
1996     8.0
1997    12.0
1998     5.0
1999     6.0
Name: monthly_visits, Length: 2000, dtype: float64
satisfaction: Missing values filled with median = 3.743458313
after filling 'satisfaction':0       3.382150
1       3.743458
2       4.195157
3       3.743458
4       3.117326
          ...
1995    3.556073
1996    2.963094
1997    3.079259
1998    3.579652
1999    1.100520
Name: satisfaction, Length: 2000, dtype: float64
churn_flag: Missing values filled with median = 0.0
after filling 'churn_flag':0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: churn_flag, Length: 2000, dtype: float64

**25.Fill missing categorical values using the mode of each categorical column.**

In [208]:
print("CATAGORICAL COLUMNS:")
print(df.select_dtypes(["object"]).columns)
print("-"*100)
for cat in df.select_dtypes(["object"]).columns:
    mode_value=df[cat].mode()[0]
    print(f"after filling missing value of catagorical column {cat} with mode {mode_value} :")
    df[cat]=df[cat].fillna(mode_value)
    print(df[cat])
    print("-"*100)

CATAGORICAL COLUMNS:
Index(['Customer ID', 'City', 'customer_segment', 'gender', 'signup_date',
       'lead_source', 'notes_text'],
      dtype='object')
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column Customer ID with mode CUST-00001 :
0       CUST-01861
1       CUST-00354
2       CUST-01334
3       CUST-00906
4       CUST-01290
           ...
1995    CUST-01131
1996    CUST-01295
1997    CUST-00861
1998    CUST-01460
1999    CUST-01127
Name: Customer ID, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column City with mode Hyderabad :
0            Pune
1       Hyderabad
2          Mumbai
3         Chennai
4          Mumbai
          ...
1995    Bengaluru
1996         Pune
1997    Hyderabad
1998    Hyderabad
1999         Pune
Name: City, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column customer_segment with mode consumer :
0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column gender with mode Male :
0         Male
1         Male
2         Male
3         Male
4         Male
         ...
1995      Male
1996      Male
1997    Female
1998      Male
1999      Male
Name: gender, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column signup_date with mode not_a_date :
0       2026-03-11
1       not_a_date
2       2024-09-20
3       2023-07-12
4       2024-08-06
           ...
1995    2024-02-26
1996    2024-08-11
1997    2023-05-27
1998    2025-01-26
1999    2024-02-22
Name: signup_date, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column lead_source with mode referral :
0       Referral
1        website
2          Email
3        Website
4       referral
          ...
1995       email
1996     Website
1997         WEB
1998       Email
1999         ???
Name: lead_source, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------
after filling missing value of catagorical column notes_text with mode normal :
0                 normal
1       follow-up needed
2                 normal
3                 normal
4                    ???
              ...
1995              normal
1996                good
1997                 ???
1998                  ok
1999                good
Name: notes_text, Length: 2000, dtype: object
----------------------------------------------------------------------------------------------------

**26.Clean the signup_date column, which contains multiple date formats and
invalid dates, and convert it to Pandas datetime.**

In [214]:
df["signup_date"] = pd.to_datetime(
    df["signup_date"],
    dayfirst=True,
    errors="coerce"
)

print(df["signup_date"])

0      2026-03-11
1             NaT
2      2024-09-20
3      2023-07-12
4      2024-08-06
          ...
1995   2024-02-26
1996   2024-08-11
1997   2023-05-27
1998   2025-01-26
1999   2024-02-22
Name: signup_date, Length: 2000, dtype: datetime64[ns]

**27.Find rows where signup_date could not be converted into a valid date.**

In [308]:
df["signup_date"]=pd.to_datetime(df["signup_date"],errors="coerce")
print("ROWS WHICH COULD NOT BE CONVERTED INTO VALID DATES")
print(df.loc[df["signup_date"].isnull()])

ROWS WHICH COULD NOT BE CONVERTED INTO VALID DATES
Empty DataFrame
Columns: [customer_id, age, income_usd, credit_score, tenure_years, monthly_visits, satisfaction, city, customer_segment, gender, is_active, churn_flag, signup_date, lead_source, notes_text]
Index: []

**28.Clean the lead_source column by standardizing values such as Website,
website, WEB, Referral, referral , Google Ads, and google_ads.**

In [236]:
print(" values in  'column lead_source':")
print(df["lead_source"].unique())
print("."*100)
print(" after standardising the values:")
df["lead_source"]=df["lead_source"].str.lower().str.strip()
df["lead_source"]=df["lead_source"].replace({"web":"website","google ads":"google_ads"})
print(df["lead_source"].value_counts())

 values in  'column lead_source':
['referral' 'websitesite' 'email' 'google_ads' 'social' 'unknown'
 'google ads' '???' 'website']
....................................................................................................
 after standardising the values:
lead_source
referral       708
email          264
websitesite    252
google_ads     242
???            141
social         140
website        130
unknown        123
Name: count, dtype: int64

**29.Create a final cleaned DataFrame containing:
• cleaned column names
• no duplicate IDs
• standardized categorical values
• numeric columns converted to numeric types
• invalid values converted to NaN
• missing values handled
• detected outliers handled**

In [302]:
print("CLEANED COLUMN NAMES:")
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
print(df.columns)
print("*"*100)
print(" TO MAKE NO DUPLICATE IDS")
print("duplicate ids:")
print(df["customer_id"].duplicated().sum())
print("*"*100)
print(" AFTER REMOVING DUPLICATED IDS:")
df.drop_duplicates(subset="customer_id",inplace=True)
print(df["customer_id"].duplicated().sum())
print("*"*100)
catagorical_col=df.select_dtypes(["object"])
print("CATAGORICAL COLUMNS:")
print(catagorical_col.columns)
print("AFTER STANDARDISING CATAGORICAL COLUMN:")
for col in catagorical_col.columns:
    print("*"*100)
    df[col]=df[col].str.strip().str.lower()
    print(f"{col} \n {df[col]}")
num_columns=["income_usd","age","credit_score","tenure_years","monthly_visits"]
for col in num_columns:
    df[col]=pd.to_numeric(df[col],errors="coerce")
    print("*"*100)
    print(f"NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : {df[col]}")
print("*"*100)
print("MISSING VALUES")
print(df.isna().sum())
for col in num_columns:
    df[col]=df[col].fillna(df[col].median())
    print(df[col])
    print("MISSING VALUE HANDLED SUCCESSFULLY in numerical column")
print("*"*100)
for col in catagorical_col.columns:
    df[col]=df[col].fillna(df[col].mode()[0])
    print(df[col])
    print("MISSING VALUE HANDLED SUCCESSFULLY in catagorical column")
import numpy as np

for col in num_columns:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    lower_limit=Q1-(1.5*IQR)
    upper_limit=Q3+(1.5*IQR)
    df.loc[(df[col]<lower_limit)|(df[col]>upper_limit),col]=np.nan

CLEANED COLUMN NAMES:
Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')
****************************************************************************************************
 TO MAKE NO DUPLICATE IDS
duplicate ids:
0
****************************************************************************************************
 AFTER REMOVING DUPLICATED IDS:
0
****************************************************************************************************
CATAGORICAL COLUMNS:
Index(['customer_id', 'city', 'customer_segment', 'gender', 'lead_source',
       'notes_text'],
      dtype='object')
AFTER STANDARDISING CATAGORICAL COLUMN:
****************************************************************************************************
customer_id
 0       cust-01861
1       cust-00354
2       cust-01334
3       cust-00906
4       cust-01290
           ...
1995    cust-01131
1996    cust-01295
1997    cust-00861
1998    cust-01460
1999    cust-01127
Name: customer_id, Length: 1980, dtype: object
****************************************************************************************************
city
 0            pune
1       hyderabad
2          mumbai
3         chennai
4          mumbai
          ...
1995    bengaluru
1996         pune
1997    hyderabad
1998    hyderabad
1999         pune
Name: city, Length: 1980, dtype: object
****************************************************************************************************
customer_segment
 0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 1980, dtype: object
****************************************************************************************************
gender
 0         male
1         male
2         male
3         male
4         male
         ...
1995      male
1996      male
1997    female
1998      male
1999      male
Name: gender, Length: 1980, dtype: object
****************************************************************************************************
lead_source
 0          referral
1       websitesite
2             email
3       websitesite
4          referral
           ...
1995          email
1996    websitesite
1997        website
1998          email
1999            ???
Name: lead_source, Length: 1980, dtype: object
****************************************************************************************************
notes_text
 0                 normal
1       follow-up-needed
2                 normal
3                 normal
4                    ???
              ...
1995              normal
1996                good
1997                 ???
1998                  ok
1999                good
Name: notes_text, Length: 1980, dtype: object
****************************************************************************************************
NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : 0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 1980, dtype: float64
****************************************************************************************************
NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : 0       45.867417
1       47.765164
2       37.854984
3       62.723578
4       37.854984
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1980, dtype: float64
****************************************************************************************************
NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : 0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit_score, Length: 1980, dtype: float64
****************************************************************************************************
NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : 0        5.274076
1        5.632826
2        4.688777
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 1980, dtype: float64
****************************************************************************************************
NUMERIC COLUMNS CONVERTED TO NUMERIC TYPES AND INVALID TO NAN : 0        5.0
1        9.0
2        8.0
3        4.0
4        5.0
        ...
1995     6.0
1996     8.0
1997    12.0
1998     5.0
1999     6.0
Name: monthly_visits, Length: 1980, dtype: float64
****************************************************************************************************
MISSING VALUES
customer_id         0
age                 0
income_usd          0
credit_score        0
tenure_years        0
monthly_visits      0
satisfaction        0
city                0
customer_segment    0
gender              0
is_active           0
churn_flag          0
signup_date         0
lead_source         0
notes_text          0
dtype: int64
0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 1980, dtype: float64
MISSING VALUE HANDLED SUCCESSFULLY in numerical column
0       45.867417
1       47.765164
2       37.854984
3       62.723578
4       37.854984
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1980, dtype: float64
MISSING VALUE HANDLED SUCCESSFULLY in numerical column
0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit_score, Length: 1980, dtype: float64
MISSING VALUE HANDLED SUCCESSFULLY in numerical column
0        5.274076
1        5.632826
2        4.688777
3        2.029634
4        2.648626
          ...
1995    14.007477
1996     0.673289
1997     2.026485
1998     7.168156
1999     9.720663
Name: tenure_years, Length: 1980, dtype: float64
MISSING VALUE HANDLED SUCCESSFULLY in numerical column
0        5.0
1        9.0
2        8.0
3        4.0
4        5.0
        ...
1995     6.0
1996     8.0
1997    12.0
1998     5.0
1999     6.0
Name: monthly_visits, Length: 1980, dtype: float64
MISSING VALUE HANDLED SUCCESSFULLY in numerical column
****************************************************************************************************
0       cust-01861
1       cust-00354
2       cust-01334
3       cust-00906
4       cust-01290
           ...
1995    cust-01131
1996    cust-01295
1997    cust-00861
1998    cust-01460
1999    cust-01127
Name: customer_id, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
0            pune
1       hyderabad
2          mumbai
3         chennai
4          mumbai
          ...
1995    bengaluru
1996         pune
1997    hyderabad
1998    hyderabad
1999         pune
Name: city, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
0         male
1         male
2         male
3         male
4         male
         ...
1995      male
1996      male
1997    female
1998      male
1999      male
Name: gender, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
0          referral
1       websitesite
2             email
3       websitesite
4          referral
           ...
1995          email
1996    websitesite
1997        website
1998          email
1999            ???
Name: lead_source, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
0                 normal
1       follow-up-needed
2                 normal
3                 normal
4                    ???
              ...
1995              normal
1996                good
1997                 ???
1998                  ok
1999                good
Name: notes_text, Length: 1980, dtype: object
MISSING VALUE HANDLED SUCCESSFULLY in catagorical column
nan
nan
nan
nan
nan

**30.Perform a final data-quality audit using Pandas and NumPy:
• Check remaining missing values
• Check duplicate rows
• Check duplicate customer IDs
• Check data types
• Check numerical ranges
• Check unique categorical values
• Confirm the final dataset is ready for analysis/ML**

In [267]:
#final data-quality audit using pandas and numpy
print("REMAINING MISSING VALUES:")
print(df.isnull().sum())
print("*"*100)
print("DUPLICATE ROWS")
print(df.duplicated().sum())
print("*"*100)
print("DUPLICATE CUSTOMER IDS")
print(df["Customer ID"].duplicated().sum())
print("DATA TYPES:")
print(df.dtypes)
Cat_col=df.select_dtypes(["object"])
for Cat in cat_col:
    print("*"*100)
    print(f"unique categorical values of '{Cat}':")
    print(f"{df[Cat].unique()}")
print("*"*100)
print("FINAL DATASET")
print(df)
print("FINAL DATASET IS READY FOR ANALYSIS")

REMAINING MISSING VALUES:
Customer ID           0
Age                   0
income_usd            0
credit Score          0
tenure_years          0
monthly_visits        0
satisfaction          0
City                  0
customer_segment      0
gender                0
is_active           340
churn_flag            0
signup_date         406
lead_source           0
notes_text            0
dtype: int64
****************************************************************************************************
DUPLICATE ROWS
0
****************************************************************************************************
DUPLICATE CUSTOMER IDS
20
DATA TYPES:
Customer ID                 object
Age                        float64
income_usd                 float64
credit Score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
City                        object
customer_segment            object
gender                      object
is_active                  float64
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object
****************************************************************************************************
unique categorical values of 'Customer ID':
['CUST-01861' 'CUST-00354' 'CUST-01334' ... 'CUST-00861' 'CUST-01460'
 'CUST-01127']
****************************************************************************************************
unique categorical values of 'City':
['Pune' 'Hyderabad' 'Mumbai' 'Chennai' 'Bengaluru' 'Kolkata' 'Delhi']
****************************************************************************************************
unique categorical values of 'customer_segment':
['consumer' 'enterprise' 'smb' 'smb.' 'unknown']
****************************************************************************************************
unique categorical values of 'gender':
['Male' 'Female']
****************************************************************************************************
unique categorical values of 'lead_source':
['referral' 'websitesite' 'email' 'google_ads' 'social' 'unknown' '???'
 'website']
****************************************************************************************************
unique categorical values of 'notes_text':
['normal' 'follow-up needed' '???' 'good customer' 'complaint!!!' 'ok'
 'VIP' 'urgent' 'good' 'late payment']
****************************************************************************************************
FINAL DATASET
     Customer ID        Age   income_usd  credit Score  tenure_years  \
0     CUST-01861  45.867417  28198.41033    660.562918      5.274076
1     CUST-00354  47.765164  61312.83129    838.000000      5.632826
2     CUST-01334  37.854984  44199.67124    613.132775      4.688777
3     CUST-00906  62.723578  56259.90961    720.236986      2.029634
4     CUST-01290  37.854984  31238.64196    549.183252      2.648626
...          ...        ...          ...           ...           ...
1995  CUST-01131  27.269512  79436.89335    633.974006     14.007477
1996  CUST-01295  41.091685  39912.37991    701.720106      0.673289
1997  CUST-00861  26.215767  24522.26545    647.799336      2.026485
1998  CUST-01460  42.300000  84103.61056    521.000000      7.168156
1999  CUST-01127  59.256095  53723.87392    576.739074      9.720663

      monthly_visits  satisfaction       City customer_segment  gender  \
0                5.0      3.382150       Pune         consumer    Male
1                9.0      3.743458  Hyderabad         consumer    Male
2                8.0      4.195157     Mumbai         consumer    Male
3                4.0      3.743458    Chennai       enterprise    Male
4                5.0      3.117326     Mumbai       enterprise    Male
...              ...           ...        ...              ...     ...
1995             6.0      3.556073  Bengaluru         consumer    Male
1996             8.0      2.963094       Pune              smb    Male
1997            12.0      3.079259  Hyderabad             smb.  Female
1998             5.0      3.579652  Hyderabad              smb    Male
1999             6.0      1.100520       Pune         consumer    Male

      is_active  churn_flag signup_date  lead_source        notes_text
0           1.0         0.0  2026-03-11     referral            normal
1           NaN         0.0         NaT  websitesite  follow-up needed
2           1.0         0.0  2024-09-20        email            normal
3           0.0         0.0  2023-07-12  websitesite            normal
4           1.0         0.0  2024-08-06     referral               ???
...         ...         ...         ...          ...               ...
1995        0.0         0.0  2024-02-26        email            normal
1996        0.0         1.0  2024-08-11  websitesite              good
1997        1.0         0.0  2023-05-27      website               ???
1998        0.0         1.0  2025-01-26        email                ok
1999        1.0         0.0  2024-02-22          ???              good

[2000 rows x 15 columns]