**Easy Level (1–10)**
Q1
Load the dataset and display the first 10 records.

In [12]:
import pandas as pd #panda library is imported
df=pd.read_excel(r"C:\Users\jyoti\Downloads\Bank_customer_churn.xlsx") #   excel file loaded
df.head(10) # to show first 10   records

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

Q2
Display the last 15 customers.

In [16]:
print("**last 15 customer are**")
df.tail(15)

**last 15 customer are**

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Q3
Show 7 random customer records.

In [17]:
print(" 7 random customer records are")
df.sample(7)

 7 random customer records are

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7285,7286,15725028,Chialuka,679,France,Male,29,3,0.00,2,1,1,63687.06,0
1369,1370,15722902,Chizuoke,652,Germany,Male,50,8,125437.64,1,1,1,17160.94,1
7999,8000,15591489,Davison,826,France,Male,26,5,142662.68,1,0,0,60285.30,0
6347,6348,15754820,Bergamaschi,637,Germany,Male,35,8,147127.81,2,1,1,84760.70,0
7974,7975,15722632,Dickson,716,Germany,Male,50,2,119655.77,1,1,1,12944.17,1
4573,4574,15693906,Abbott,645,France,Female,24,3,34547.82,1,1,1,11638.17,0
7443,7444,15707042,Dellucci,634,France,Female,24,2,87413.19,1,1,0,63340.65,0

Q4
Print complete dataset information and identify:
• Total columns
• Data type of each column
• Missing values

In [29]:
print(" complete dataset information . . . .")
print(df.info())
print("total columns are . . . . ")
print(df.columns)
print(" data types of each columns are: . .. . . . ")
print(df.dtypes)
print(" missing values are . . . . ")
print(df.isnull().sum())

 complete dataset information . . . .
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
total columns are . . . .
Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')
 data types of each columns are: . .. . . .
RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object
 missing values are . . . .
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Q5
Find missing values in every column.

In [30]:
print("missing values of each columns are:")
print(df.isnull().sum())

missing values of each columns are:
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Q6
Display only numerical columns.

In [103]:
print(" displaying only numerical columns")
DF=df.select_dtypes(include=["number"])
DF

 displaying only numerical columns

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1,15634602,619,42.0,2,0.00,1,1,1,101348.88
1,2,15647311,608,41.0,1,83807.86,1,0,1,112542.58
2,3,15619304,502,42.0,8,159660.80,3,1,0,113931.57
3,4,15701354,699,39.0,1,0.00,2,0,0,93826.63
4,5,15737888,850,43.0,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39.0,5,0.00,2,1,0,96270.64
9996,9997,15569892,516,35.0,10,57369.61,1,1,1,101699.77
9997,9998,15584532,709,36.0,7,0.00,1,0,1,42085.58
9998,9999,15682355,772,42.0,3,75075.31,2,1,0,92888.52
9999,10000,15628319,792,28.0,4,130142.79,1,1,0,38190.78

Q7
Generate the statistical summary of numerical columns.

In [39]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

Q8
Find duplicate rows and print how many exist.

In [49]:

df[df.duplicated()]# to show duplicate rows
print(df.duplicated().sum()) # to find number of existing duplicated rows

0

Q9
Remove duplicate rows and store the cleaned dataset.

In [54]:
cleaned_datset=df. drop_duplicates()
cleaned_datset

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

Q10
Count how many customers have exited and how many have not exited.

In [66]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

**Medium Level (11–20)**
Q11
Rename the following columns:
CustomerId → Customer_ID
CreditScore → Credit_Score
EstimatedSalary → Salary
Exited → Churn

In [69]:
print(" renaming columns")
df.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"})

 renaming columns

,RowNumber,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

Q12
Add the prefix
Bank_
to every column name.

In [72]:
df.add_prefix("Bank_")

,Bank_RowNumber,Bank_CustomerId,Bank_CreditScore,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

Q13
Convert the Age column into float datatype.

In [80]:
df["Age"]=df["Age"].astype("float")
df.dtypes["Age"]

dtype('float64')

Q14
Convert the Exited column into string datatype.

In [81]:
df["Exited"]=df["Exited"].astype("string")
df["Exited"]

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: string

Q15
Suppose the Balance column has missing values.
Replace them using the mean of the Balance column.

In [92]:
print(" finding mean of Balance column")
mean=df["Balance"].mean()
print(mean)
print(" Filling the missing value of  Balance  column with mean:")
df["Balance"]=df["Balance"].fillna(mean)

print(df["Balance"])#verify

 finding mean of Balance column
76485.889288
 Filling the missing value of  Balance  column with mean:
0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [93]:
df["Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

Q18
Create a new DataFrame by dropping these columns:
RowNumber
CustomerId
Display the first 10 rows.

In [97]:
# Create a new DataFrame by dropping the columns
df_new = df.drop(["RowNumber", "CustomerId"], axis=1)

# Display the first 10 rows
print(df_new.head(10))

   CreditScore   Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  42.0       2       0.00              1          1
1          608  41.0       1   83807.86              1          0
2          502  42.0       8  159660.80              3          1
3          699  39.0       1       0.00              2          0
4          850  43.0       2  125510.82              1          1
5          645  44.0       8  113755.78              2          1
6          822  50.0       7       0.00              2          1
7          376  29.0       4  115046.74              4          1
8          501  44.0       4  142051.07              2          0
9          684  27.0       2  134603.88              1          1

   IsActiveMember  EstimatedSalary Exited
0               1        101348.88      1
1               1        112542.58      0
2               0        113931.57      1
3               0         93826.63      0
4               1         79084.10      0
5               0        149756.71      1
6               1         10062.80      0
7               0        119346.88      1
8               1         74940.50      0
9               1         71725.73      0

Q18
Rename NumOfProducts to Products and HasCrCard to CreditCard.

In [109]:
df.rename(columns={"NumOfProducts":"Products","HasCrCard":"CreditCard"})

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28.0,4,130142.79,1,1,0,38190.78,0

**Hard Level (21–30)**

**Q21 (Real Company Task)**
Your manager wants cleaner column names.
Rename every column as follows:
RowNumber → Row_No
CustomerId → Customer_ID
Surname → Last_Name
CreditScore → Credit_Score
Geography → Country
Gender → Sex
EstimatedSalary → Salary
Exited → Target
Display the first five rows.

In [119]:
df.rename(columns={"RowNumber":"Row_No","CustomerId":"Customer_ID","Surname":"Last_Name","CreditScore": "Credit_Score","Geography":"Country","Gender":"Sex"\
                   ,"EstimatedSalary":"Salary","Exited":"Target"},inplace=True)
df.head()

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,619,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0

Q22
Create a new DataFrame that contains only numeric columns.
Then generate its statistical summary.

In [123]:
new =df.select_dtypes(include=["number"])
print(new.describe())# generate  statistical summery

,Row_No,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000

Q23
Your company received duplicate customer records.
Tasks:
• Count duplicates.
• Remove duplicates.
• Display dataset information after cleaning.

In [127]:
print(df.duplicated().sum()) # count duplicated
print(" after removing  duplicated records")
print(df.drop_duplicates())# removes duplicates
print(" information of datas")
df.info()

0
 after removing  duplicated records
      Row_No  Customer_ID  Credit_Score   Age  Tenure    Balance  \
0          1     15634602           619  42.0       2       0.00
1          2     15647311           608  41.0       1   83807.86
2          3     15619304           502  42.0       8  159660.80
3          4     15701354           699  39.0       1       0.00
4          5     15737888           850  43.0       2  125510.82
...      ...          ...           ...   ...     ...        ...
9995    9996     15606229           771  39.0       5       0.00
9996    9997     15569892           516  35.0      10   57369.61
9997    9998     15584532           709  36.0       7       0.00
9998    9999     15682355           772  42.0       3   75075.31
9999   10000     15628319           792  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88      1
1                 1          0               1  112542.58      0
2                 3          1               0  113931.57      1
3                 2          0               0   93826.63      0
4                 1          1               1   79084.10      0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64      0
9996              1          1               1  101699.77      0
9997              1          0               1   42085.58      1
9998              2          1               0   92888.52      1
9999              1          1               0   38190.78      0

[10000 rows x 11 columns]
 information of datas
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Credit_Score    10000 non-null  int64
 3   Age             10000 non-null  float64
 4   Tenure          10000 non-null  int64
 5   Balance         10000 non-null  float64
 6   NumOfProducts   10000 non-null  int64
 7   HasCrCard       10000 non-null  int64
 8   IsActiveMember  10000 non-null  int64
 9   Salary          10000 non-null  float64
 10  Target          10000 non-null  string
dtypes: float64(3), int64(7), string(1)
memory usage: 859.5 KB

Q24
Management wants every column name to begin with
Customer_

Apply this transformation using the appropriate method.

In [129]:
df.add_prefix("Customer_")

,Customer_Row_No,Customer_Customer_ID,Customer_Credit_Score,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_Salary,Customer_Target
0,1,15634602,619,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28.0,4,130142.79,1,1,0,38190.78,0

Q25
After renaming the columns, convert
Age
Balance
Salary
to float datatype.
Print dataset information.

In [136]:
print(df.rename(columns={"Age":"age","Balance":"balance","Salary":"salary"}))
print("converting these into datatype float")
df[["Age","Balance","Salary"]].astype("float")

      Row_No  Customer_ID  Credit_Score   age  Tenure    balance  \
0          1     15634602           619  42.0       2       0.00
1          2     15647311           608  41.0       1   83807.86
2          3     15619304           502  42.0       8  159660.80
3          4     15701354           699  39.0       1       0.00
4          5     15737888           850  43.0       2  125510.82
...      ...          ...           ...   ...     ...        ...
9995    9996     15606229           771  39.0       5       0.00
9996    9997     15569892           516  35.0      10   57369.61
9997    9998     15584532           709  36.0       7       0.00
9998    9999     15682355           772  42.0       3   75075.31
9999   10000     15628319           792  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     salary Target
0                 1          1               1  101348.88      1
1                 1          0               1  112542.58      0
2                 3          1               0  113931.57      1
3                 2          0               0   93826.63      0
4                 1          1               1   79084.10      0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64      0
9996              1          1               1  101699.77      0
9997              1          0               1   42085.58      1
9998              2          1               0   92888.52      1
9999              1          1               0   38190.78      0

[10000 rows x 11 columns]
converting these into datatype float

       Age    Balance     Salary
0     42.0       0.00  101348.88
1     41.0   83807.86  112542.58
2     42.0  159660.80  113931.57
3     39.0       0.00   93826.63
4     43.0  125510.82   79084.10
...    ...        ...        ...
9995  39.0       0.00   96270.64
9996  35.0   57369.61  101699.77
9997  36.0       0.00   42085.58
9998  42.0   75075.31   92888.52
9999  28.0  130142.79   38190.78

[10000 rows x 3 columns]

Q26
Assume Credit_Score   contains missing values.
Replace them with the median CreditScore.

In [145]:
median=df["Credit_Score"].median()
print(median)
df["Credit_Score"]=df["Credit_Score"].fillna(median)
print(df["Credit_Score"])

652.0
0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: Credit_Score, Length: 10000, dtype: int64

Q27
Assume Salary  contains missing values.
Replace them with the mean salary.
Then print the first eight rows.

In [151]:
mean=df["Salary"].mean()
print(mean)
a=df["Salary"].fillna(mean)
print(a)

100090.239881
0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: Salary, Length: 10000, dtype: float64

Q28 (Data Cleaning Challenge)
Perform all the following:
• Remove duplicate rows.
• Rename Exited to Target.
• Convert Target to string.
• Display dataset information.

In [161]:
print(" Removing duplicate row: . . . ")
print(df.drop_duplicates)
print("after renaming Exited to target:")
df.rename(columns={"Exited":"Target"})
df["Target"].astype("string")#  to convert Target  column datatype to string
df.info()

 Removing duplicate row: . . .
<bound method DataFrame.drop_duplicates of       Row_No  Customer_ID  Credit_Score   Age  Tenure    Balance  \
0          1     15634602           619  42.0       2       0.00
1          2     15647311           608  41.0       1   83807.86
2          3     15619304           502  42.0       8  159660.80
3          4     15701354           699  39.0       1       0.00
4          5     15737888           850  43.0       2  125510.82
...      ...          ...           ...   ...     ...        ...
9995    9996     15606229           771  39.0       5       0.00
9996    9997     15569892           516  35.0      10   57369.61
9997    9998     15584532           709  36.0       7       0.00
9998    9999     15682355           772  42.0       3   75075.31
9999   10000     15628319           792  28.0       4  130142.79

      NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0                 1          1               1  101348.88      1
1                 1          0               1  112542.58      0
2                 3          1               0  113931.57      1
3                 2          0               0   93826.63      0
4                 1          1               1   79084.10      0
...             ...        ...             ...        ...    ...
9995              2          1               0   96270.64      0
9996              1          1               1  101699.77      0
9997              1          0               1   42085.58      1
9998              2          1               0   92888.52      1
9999              1          1               0   38190.78      0

[10000 rows x 11 columns]>
after renaming Exited to target:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_No          10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Credit_Score    10000 non-null  int64
 3   Age             10000 non-null  float64
 4   Tenure          10000 non-null  int64
 5   Balance         10000 non-null  float64
 6   NumOfProducts   10000 non-null  int64
 7   HasCrCard       10000 non-null  int64
 8   IsActiveMember  10000 non-null  int64
 9   Salary          10000 non-null  float64
 10  Target          10000 non-null  string
dtypes: float64(3), int64(7), string(1)
memory usage: 859.5 KB

Q29 (Transformation Challenge)
Create a copy of the dataset.

Perform these transformations:
• Rename Gender to CustomerGender
• Add prefix Bank_
• Display first 10 rows

In [185]:
copy=df.copy()# create  copy of dataset
print(copy)
print(" Renaming gender to CustomerGender")
copy.rename(columns={"gender":"CustomerGender"})
print(df.add_prefix("Bank_"))# adding  prefix "Bank_" to each column
df.head(10)

      Customer_ID  Credit_Score   Age  Tenure    Balance  NumOfProducts  \
0        15634602           619  42.0       2       0.00              1
1        15647311           608  41.0       1   83807.86              1
2        15619304           502  42.0       8  159660.80              3
3        15701354           699  39.0       1       0.00              2
4        15737888           850  43.0       2  125510.82              1
...           ...           ...   ...     ...        ...            ...
9995     15606229           771  39.0       5       0.00              2
9996     15569892           516  35.0      10   57369.61              1
9997     15584532           709  36.0       7       0.00              1
9998     15682355           772  42.0       3   75075.31              2
9999     15628319           792  28.0       4  130142.79              1

      HasCrCard  IsActiveMember     Salary Target
0             1               1  101348.88      1
1             0               1  112542.58      0
2             1               0  113931.57      1
3             0               0   93826.63      0
4             1               1   79084.10      0
...         ...             ...        ...    ...
9995          1               0   96270.64      0
9996          1               1  101699.77      0
9997          0               1   42085.58      1
9998          1               0   92888.52      1
9999          1               0   38190.78      0

[10000 rows x 10 columns]
 Renaming gender to CustomerGender
      Bank_Customer_ID  Bank_Credit_Score  Bank_Age  Bank_Tenure  \
0             15634602                619      42.0            2
1             15647311                608      41.0            1
2             15619304                502      42.0            8
3             15701354                699      39.0            1
4             15737888                850      43.0            2
...                ...                ...       ...          ...
9995          15606229                771      39.0            5
9996          15569892                516      35.0           10
9997          15584532                709      36.0            7
9998          15682355                772      42.0            3
9999          15628319                792      28.0            4

      Bank_Balance  Bank_NumOfProducts  Bank_HasCrCard  Bank_IsActiveMember  \
0             0.00                   1               1                    1
1         83807.86                   1               0                    1
2        159660.80                   3               1                    0
3             0.00                   2               0                    0
4        125510.82                   1               1                    1
...            ...                 ...             ...                  ...
9995          0.00                   2               1                    0
9996      57369.61                   1               1                    1
9997          0.00                   1               0                    1
9998      75075.31                   2               1                    0
9999     130142.79                   1               1                    0

      Bank_Salary Bank_Target
0       101348.88           1
1       112542.58           0
2       113931.57           1
3        93826.63           0
4        79084.10           0
...           ...         ...
9995     96270.64           0
9996    101699.77           0
9997     42085.58           1
9998     92888.52           1
9999     38190.78           0

[10000 rows x 10 columns]

,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,15634602,619,42.0,2,0.00,1,1,1,101348.88,1
1,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0
2,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1
3,15701354,699,39.0,1,0.00,2,0,0,93826.63,0
4,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0
5,15574012,645,44.0,8,113755.78,2,1,0,149756.71,1
6,15592531,822,50.0,7,0.00,2,1,1,10062.80,0
7,15656148,376,29.0,4,115046.74,4,1,0,119346.88,1
8,15792365,501,44.0,4,142051.07,2,0,1,74940.50,0
9,15592389,684,27.0,2,134603.88,1,1,1,71725.73,0

In [186]:
**Bonus Challenge (Create New Columns)**
These require creating new columns using basic Pandas assignment along with the methods
you've learned.
B1
Create a new column:
TotalMoney = Balance + EstimatedSalary

B2
Create a new column:
DoubleScore = CreditScore × 2

B3
Create a new column:
AgeAfter10Years = Age + 10

B4
Create a new column:
HasBalance = Balance
Replace missing values in this new column using the mean.

B5

Sumit Sir Notes
Create a new column:
SalaryInLakhs = EstimatedSalary / 100000

SyntaxError: unterminated string literal (detected at line 3) (189397375.py, line 3)

B1
Create a new column:
TotalMoney = Balance + Salary

In [193]:
df["TotalMoney"]=df["Balance"] + df["Salary"]
df.head()

,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney
0,15634602,619,42.0,2,0.00,1,1,1,101348.88,1,101348.88
1,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0,196350.44
2,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1,273592.37
3,15701354,699,39.0,1,0.00,2,0,0,93826.63,0,93826.63
4,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0,204594.92


B2
Create a new column:
DoubleScore = Credit_Score × 2

In [195]:
df["DoubleScore"]=df["Credit_Score"]*2
df.head()

,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore
0,15634602,619,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238
1,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216
2,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004
3,15701354,699,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398
4,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700

B3
Create a new column:
AgeAfter10Years = Age + 10

In [199]:
df["AgeAfter10Years"]=df["Age"]+10 #AgeAfter10Years = Age + 10
df.head()# to verify it   by diplaying first 5 rows

,Customer_ID,Credit_Score,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore,AgeAfter10Years
0,15634602,619,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238,52.0
1,15647311,608,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51.0
2,15619304,502,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52.0
3,15701354,699,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398,49.0
4,15737888,850,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53.0

B4
Create a new column:
HasBalance = Balance
Replace missing values in this new column using the mean.

In [202]:
df["HasBalance"]=df["Balance"]# new column created  with column name HasBalance
mean=df["HasBalance"].mean()# find the mean of new column HasBalance
df["HasBalance"].fillna(mean)

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: HasBalance, Length: 10000, dtype: float64

B5

Create a new column:
SalaryInLakhs = EstimatedSalary / 100000

In [ ]:
df["SalaryInLakhs"]=df["