1. Load the dataset using the appropriate Pandas method and store it in a
variable named df.

In [38]:
import pandas as pd
df=pd.read_excel(r"C:\Users\jyoti\Downloads\Bank_customer_churn.xlsx")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

2.Display the first 8 rows of the dataset.

In [39]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

3.Display the last 12 rows of the dataset.

In [40]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

4. Show 10 random rows from the dataset.

In [43]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5522,5523,15686696,Brown,817,France,Female,37,6,81070.34,2,1,0,80985.88,0
4805,4806,15745452,Sun,651,Germany,Male,41,1,90218.11,1,1,0,174337.68,0
4559,4560,15668248,Quinn,528,Germany,Female,62,7,133201.17,1,0,0,168507.68,1
7227,7228,15566495,Hanson,704,Spain,Female,24,2,0.00,1,1,0,35600.25,1
7350,7351,15713160,Lin,669,Spain,Male,25,7,157228.61,2,1,0,124382.90,0
5461,5462,15589563,Purdy,531,Spain,Male,31,2,118899.45,2,0,0,41409.36,0
5812,5813,15587835,Osinachi,850,France,Male,41,3,136416.82,1,0,1,57844.26,0
5958,5959,15741719,DeRose,540,France,Female,40,3,165298.12,1,0,1,199862.75,0
488,489,15731744,Carslaw,692,France,Male,30,2,0.00,2,0,1,130486.57,0
1675,1676,15658459,Bates,784,Spain,Male,33,10,0.00,2,1,0,162022.47,0

5. Find the shape of the dataset.
o How many rows are there?
o How many columns are there?

In [44]:
df.shape # find number of rows and columns

(10000, 14)

In [45]:
df.columns #shows list of columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

6. Display complete information about the dataset using one method.
o Number of non-null values
o Data types
o Memory usage

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

7. Print the names of all columns in the dataset.

In [52]:
z=df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

8. Find the data type of every column.

In [57]:

df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

9. Check for missing values in every column using:
o isnull().sum()
o isna().sum()

In [58]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [59]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

10.Select only one column:
o CreditScore

In [63]:
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

11.Select the following multiple columns:
o CustomerId
o Surname
o Balance
o Exited

In [67]:
df[['CustomerId', 'Surname', 'Balance', 'Exited']]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

12.Display only numeric columns using select_dtypes().

In [70]:
df.select_dtypes(include=["number"])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

13.Generate the statistical summary of all numeric columns using describe().

In [71]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

14.Check for duplicate rows in the dataset.
o How many duplicate rows exist?

o Remove all duplicate rows.

In [74]:
df.duplicated().sum()

np.int64(0)

In [78]:
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

15.Count the number of customers in each class of the Exited column using
value_counts().

In [81]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

**Operators + Loops (1-5)**

1. Take two numbers from user. Perform all arithmetic operations and also check
which number is greater using comparison operators.

In [88]:
num1=int(input("enter a number"))
num2=int(input("enter 2nd number"))
print(f"addition of {num1} and {num2} is {num1+num2}") 
print(f"Multiplication of {num1} and {num2} is {num1 * num2}") 
print(f" division of {num1} and {num2} is {num1%num2}") 
print(f"subtraction of {num1} and {num2} is {num1-num2}") 
print(f" power :{ pow(num1,num2)}")
print("-"*50)
print("comparing two  number:")
if num1>num2:
    print(f"{num1} is greater" )
else:
    print(f"{num2} is greater")

enter a number 8
enter 2nd number 2

addition of 8 and 2 is 10
Multiplication of 8 and 2 is 16
 division of 8 and 2 is 0
subtraction of 8 and 2 is 6
 power :64
--------------------------------------------------
comparing two  number:
8 is greater

2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
completely when number 40 is reached using break.

In [94]:
for num in range(1,51):
   
    if num%5==0:
        continue
    if num==40:
        break
    print(num)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49

3. Take numbers from user until they enter negative number. Calculate sum and
average using while loop.

In [103]:
count=0
sum=0
while True:
  num=int(input("enter a number"))
  

  if num<0:
        break
  sum+=num
  count+=1

print(f" sum of entered number is {sum}")
average=sum/count
print(f"average of numbers is {average}")

enter a number 9
enter a number 9
enter a number 9
enter a number -4

 sum of entered number is 27
average of numbers is 9.0

4. Print the following pattern using nested loops:
*****
****
***
**
*

In [111]:

for i in range(5,0,-1):# using one loop
    
    
       print("*"*i)

*****
****
***
**
*

In [121]:
# using nested loop
for i in range(5,0,-1):
    for j in range(i):
        print("*",end="") #end="" means:After printing *, do not move to the next line.
    print()

*****
****
***
**
*

**Data Types & Methods (6-9)**

6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
spaces with -, and check if it starts with “Hello”.

In [133]:
string=input("enter a string")
count=0
for i in string:
    if  i =="a":
        count+=1
print(f"occurance of a in {string} is{count}")
s=string.upper()
print(f" after converting {string} into upper case is {s}")
a=string.replace(" ","-")
print(f" after replacing space with - {a}")
print("starts with hello :::",string.startswith("Hello"))

enter a string hiii i am monu

occurance of a in hiii i am monu is1
 after converting hiii i am monu into upper case is HIII I AM MONU
 after replacing space with - hiii-i-am-monu
starts with hello ::: False

7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
and reverse.

In [154]:
list=[1,2,3,4,5,6]
list.append(7)
print(f" after adding a element in list {list}")
list.insert(2,90)
print(f" after inserting  a element in list {list}")
list.remove(5)
print(f" after removing  a element in list {list}")
list.pop(6)
print(f" after poping  a element in list {list}")
list.sort( reverse =True)
print(f" after  sorting the list in descending order:{list}")
list.sort()
print(f" after  sorting the list in reverse order:{list}")

 after adding a element in list [1, 2, 3, 4, 5, 6, 7]
 after inserting  a element in list [1, 2, 90, 3, 4, 5, 6, 7]
 after removing  a element in list [1, 2, 90, 3, 4, 6, 7]
 after poping  a element in list [1, 2, 90, 3, 4, 6]
 after  sorting the list in descending order:[90, 6, 4, 3, 2, 1]
 after  sorting the list in reverse order:[1, 2, 3, 4, 6, 90]

8. Create a dictionary of 4 students (name:marks). Print only those students who
scored more than 80 using items().

In [162]:
dict={"biki":90,"munu":89,"gulu":78,"sipa":67}
for keys,marks in dict.items():
    if marks>80:
        print(f"{keys}:{marks}")

biki:90
munu:89

9. Create two sets and perform union, intersection, difference. Also add and discard
elements.

In [170]:
set1={"flower","fruits","seeds","tree","plants"}
set2={"cat","dog","insect","coackroaches","plants"}
print("union of two sets is:")
a=set1.union(set2)
print(a)
print("intersection  of two sets is:")
b=set1.intersection(set2)
print(b)
c=set1-set2
print(f" diffrence of  set 1 and set 2is {c}")
set1.add("fungi")
print(f"after adding  an element in set 1 is {set1}")
set1.discard("fruits")
print(f" after dicarding an element from set1 is {set1}")

union of two sets is:
{'flower', 'tree', 'dog', 'seeds', 'fruits', 'plants', 'cat', 'coackroaches', 'insect'}
intersection  of two sets is:
{'plants'}
 diffrence of  set 1 and set 2is {'fruits', 'flower', 'tree', 'seeds'}
after adding  an element in set 1 is {'fruits', 'flower', 'tree', 'plants', 'fungi', 'seeds'}
 after dicarding an element from set1 is {'flower', 'tree', 'plants', 'fungi', 'seeds'}

**OOP + Encapsulation (10-14)**

10. Create a class Student with private attribute __marks. Add getter and setter with
validation (0–100).

In [187]:
class Student:
    def __init__(self,marks):
        self.__marks=marks
    def get_marks(self):
        return self.__marks
    def set_marks(self,marks):
       if marks in range(0,101):
           self.__marks=marks
           return f" marks:{self.__marks}"
       else:
           print("enter number between 0 to 100")
student=Student(67)
student.get_marks()
student.set_marks(90)
student.set_marks(-2)

enter number between 0 to 100

11. Create class BankAccount with private __balance. Add deposit and withdraw
methods. Raise custom exception if balance becomes negative.

In [195]:
class balanceNegativeError(Exception):
    pass
class BankAccount:
    def __init__(self,balance):
        self.__balance=balance
        
    def  deposit(self,amount):
        self.__balance+=amount
        print(f" remaining balance after depositing{amount} is :{self.__balance}")
    def withdraw(self,amount):
        
        self.__balance-=amount
        print(f" remaining balance afterwithdraw {amount} is :{self.__balance}")
        if self.__balance<0:
            raise balanceNegativeError (" balance is in negative")

try:
    bankAccount=BankAccount(10000)
    bankAccount.deposit(6000)
    bankAccount.withdraw(18000)
except balanceNegativeError as e :
    print(e)

 remaining balance after depositing6000 is :16000
 remaining balance afterwithdraw 18000 is :-2000
 balance is in negative

12. Create class Employee with class attribute company_name. Show that it is
shared by all objects. Also update the class attribute.

In [215]:
class Employee:
    company_name="ASP OL MEDIA"
    def __init__(self,name):
        self.name=name
employee=Employee("riya")
employee1=Employee("riym")
employee.company_name
employee1.company_name
Employee.company_name = "tcs"
employee.company_name

'tcs'

13. Create class Product with private __price. Add getter and setter. Setter should
not allow price less than 100.

In [222]:
class Product:
    def __init__(self,price):
        self.__price=price
    def get_price(self):
        return self.__price
    def set_price(self,price):
        if price>=100:
            self.__price=price
            return self.__price
        else:
            print(" price should not be less than 100")
product=Product(700)
product.get_price()
product.set_price(-7)

 price should not be less than 100

14. Create class Rectangle with private length and width. Add method to calculate
area and perimeter.

In [226]:
class Rectangle:
    def __init__(self,length,breadth):
        self.__length=length
        self.__breadth=breadth
    def get_length(self):
        return self.__length
    def get_breadth(self):
        return self.__breadth
        
    def area(self):
        area=self.__length*self.__breadth
        print(f"area of rectangle is { area}")
    def perimeter(self):
        perimeter=2*(self.__length+self.__breadth)
        print(f" perimeter of rectangle is  {perimeter}")
rectangle=Rectangle(5,10)
rectangle.area()
rectangle.perimeter()

area of rectangle is 50
 perimeter of rectangle is  30

**Inheritance + Abstraction + super() (15-19)**

15. Create single level inheritance: Person → Student. Use super() in constructor.

In [233]:
class Person:
    def __init__(self,name):
        self.name=name
    def display(self):
        print("name is:",self.name)
class Student(Person):
    def __init__(self,student_name):
        super().__init__(student_name)
        
    
student=Student("shubhra")
student.name

'shubhra'

16. Create multi-level inheritance: Person → Employee → Manager. Override a
method at each level.

In [242]:
class Person:
    def __init__(self,name):
        self.name=name
    def display(self):
        print(" i love to play")
class Employee(Person):
    def __init__(self,name,age):
        super().__init__(name)
        self.age=age
    def display(self):
        super().display()
        print("i love to study")
class Manager(Employee):
    def __init__(self,name,age,gender):
        super().__init__(name,age)
        self.gender=gender
    def display(self):
        super().display()
        print(" i love to paint")
manager=Manager("shubhra",22,"Male")
manager.display()
manager.age

 i love to play
in love to study
 i love to paint

22

17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
method.

In [247]:
class  Animal:
    def sound(self):
        print(" animal makes sound")
class Dog(Animal):
    def sound(self):
        super().sound()
        print("dog barks")
class Cat(Animal):
    def sound(self):
        super().sound()
        print("cat meows")
dog=Dog()
dog.sound()
cat=Cat()
cat.sound()

 animal makes sound
dog barks
 animal makes sound
cat meows

18. Create abstract class Shape with abstract method area(). Implement it in Circle
and Square using super().

In [257]:
from abc import ABC,abstractmethod
class Shape(ABC):
    @abstractmethod
    def  area(self):
        pass
class Circle(Shape):
    def area(self,r):
        super().area()
        area=3.14*r*r
        print("area of circle is :",area)
class Square(Shape):
    def area(self,length):
        super().area()
        area=length*length
        print("area of square is",area)

circle=Circle()
circle.area(6)
square=Square()
square.area(3)

area of circle is : 113.03999999999999
area of square is 9

19. Create multiple inheritance with two classes Father and Mother. Create child
class and resolve method conflict.

In [265]:
class Father:
    def show(self):
        print(" father  always work hard")
class Mother:
    def show(self):
        print("mother too works hard")
class Child(Mother,Father):
    def show(self):
        super().show()
        print(" child learn to work from parents")
child=Child()
child.show()
print(Child.mro())

mother too works hard
 child learn to work from parents
[<class '__main__.Child'>, <class '__main__.Mother'>, <class '__main__.Father'>, <class 'object'>]

**Overloading + Exception + File Handling (20-25)**

20. Create a class Calculator that can add 2 or 3 numbers (method overloading
using *args).

In [278]:
class Calculator:
    def add(self, *args):
        sum=0
        for i in args:
             sum+=i
        print("sum is :",sum)

calculator = Calculator()
calculator.add(2,3,6)

sum is : 11

21. Create class Point and overload + and > operators.

In [293]:
class Point:
    def __init__(self,x,y):# init method to initialize the variable
        self.x=x
        self.y=y
    def __add__(self,others): # dunder or doube underscore add method to add two object
        return Point(self.x+others.x,self.y+others.y)

    def __gt__(self,others): # greater than/  dunder gt method to compare two object
        return((self.x+self.y)>(others.x+others.y))
    def display(self): #  dsiplay method to return the  of addition of two method
        return (self.x,self.y)
    
point=Point(2,3)
point1=Point(3,4)
point>point1
c=point+point1
c.display()
point>point1

False

22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
multiple except blocks.

In [297]:
try:
    a=int(input("enter a number"))
    b=int(input("enter 2nd number"))
    list=[1,2,3,4,5,6]
    c=a/b
    print(f" after dividing two number{a} with {b}:{c}")
    print(f"  value of index  7 is{list[7]}")
except  ZeroDivisionError as e:
    print(f" error:{e}")
except ValueError as e:
    print(f" error:{e}")
except IndexError as e:
    print(f" error:{e}")

enter a number 8
enter 2nd number 9

 after dividing two number8 with 9:0.8888888888888888
 error:list index out of range

23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

In [302]:
class InvalidAgeError(Exception):
    pass
class Age:
    def __init__(self,age):
        self.age=age
    def  show(self):
        if self.age <18:
            raise InvalidAgeError(" age cannot be less than 18")
        else:
            print( self.age)
try:
    age=Age(90)
    age.show()
except InvalidAgeError as e:
    print(e)

90

24. Write a program to read a file, count number of words, and write the count into
another file.

In [317]:
with open("text.txt","w") as file:
     file.write(" hii  i am shubhra")
with open ("text.txt","r") as file:
    content=file.read()
    z=content.split()
    print(z)
    x=len(z)
    print(x)
with open("store.txt","w")as file:
    file.write(f"{x}")
with open("store.txt","r")as file:
    print(file.read())

['hii', 'i', 'am', 'shubhra']
4
4

25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
Handle FileNotFoundError.

In [337]:
while True:
    print("1.Read")
    print("2.write")
    print("3.append")
    print("4.exit")
    choice=int(input("enter your choice"))
               
    try:
        
        if  choice== 1:
            with open("text.txt","r") as file:
                   print(file.read())
        if choice==2:
            with open("text.txt","w") as file:
                data=input("enter your data")
                file.write(data)
        if choice==3:
            with open("text.txt","a") as file:
                data=input("enter  your data")
                file.write(data)
        if choice==4:
            print("exiting . . . . . . . . . . . ")          
            break
    except Exception as e:
            print(e)

1.Read
2.write
3.append
4.exit

enter your choice 1

hii
1.Read
2.write
3.append
4.exit

enter your choice 2
enter your data shubhra

1.Read
2.write
3.append
4.exit

enter your choice 1

shubhra
1.Read
2.write
3.append
4.exit

enter your choice 3
enter  your data hiiii shubhra myself gita

1.Read
2.write
3.append
4.exit

enter your choice 1

shubhrahiiii shubhra myself gita
1.Read
2.write
3.append
4.exit

enter your choice 4

exiting . . . . . . . . . . .

26. Create a class Student with private marks list.
• Setter should validate each mark (0-100)
• Overload > operator to compare two students based on average
• Raise custom exception if marks list is empty

In [365]:
class ListIsEmpty(Exception):
    pass
class Student:
    def __init__(self,*marks):
        self.__marks=list(marks)
    def  get_marks(self):
        return self.__marks
    def set_marks(self,marks):
         for mark in marks:
            if mark in range(0,101):
                self.__marks.append(mark)
             
            else:
               print(" marks shoud be between (0-100)")
    
    def __gt__(self,others):
        if len(self.__marks)==0 or len(others.__marks)==0:
           raise ListIsEmpty(" list cannot be empty")
        else:
           return(sum(self.__marks)/len(self.__marks))>(sum(others.__marks)/len(others.__marks))
try:
    student= Student(1,2,3)
    student1= Student(4,5,6)
    
    print(student.get_marks())
    print(student>student1)
    
except ListIsEmpty as e:
    print(e)

[1, 2, 3]
False

27. Write a menu-driven banking system using OOP + File Handling. Store account
details in a file. Handle FileNotFoundError, ValueError, and custom exceptions.

In [ ]:
class InsufficientBalance(Exception):
    pass


class BankSystem:
    def __init__(self, name, age, balance=0):
        self.name = name
        self.age = age
        self.balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
        else:
            raise ValueError("Amount should be greater than 0")

    def withdraw(self, amount):
        if amount > 0:
            if amount <= self.balance:
                self.balance -= amount
                return self.balance
            else:
                raise InsufficientBalance(
                    "Balance is less than amount entered"
                )
        else:
            raise ValueError("Amount should not be less than 0")

    def show(self):
        print(f"Name: {self.name}")
        print(f"Age: {self.age}")
        print(f"Balance: {self.balance}")


while True:
    print("1. Create account")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Show details")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    try:
        if choice == 1:
            name = input("Enter your name: ")
            age = int(input("Enter age: "))
            balance = int(input("Enter balance to store: "))

            account = BankSystem(name, age, balance)

            with open("store.txt", "w") as file:
                file.write(f"{name},{age},{balance}")

            print("Account created successfully")

        elif choice == 2:
            with open("store.txt", "r") as file:
                data = file.read()

            name, age, balance = data.split(",")

            amount = int(input("Enter amount to deposit: "))

            account = BankSystem(
                name,
                int(age),
                float(balance)
            )

            account.deposit(amount)

            with open("store.txt", "w") as file:
                file.write(
                    f"{account.name},{account.age},{account.balance}"
                )

        elif choice == 3:
            with open("store.txt", "r") as file:
                data = file.read()

            name, age, balance = data.split(",")

            amount = int(input("Enter amount to withdraw: "))

            account = BankSystem(
                name,
                int(age),
                float(balance)
            )

            account.withdraw(amount)

            with open("store.txt", "w") as file:
                file.write(
                    f"{account.name},{account.age},{account.balance}"
                )

        elif choice == 4:
            with open("store.txt", "r") as file:
                data = file.read()

            name, age, balance = data.split(",")

            account = BankSystem(
                name,
                int(age),
                float(balance)
            )

            account.show()

        elif choice == 5:
            break

    except FileNotFoundError:
        print("Account not found. Create an account first.")

    except ValueError as e:
        print(e)

    except InsufficientBalance as e:
        print(e)

1. Create account
2. Deposit
3. Withdraw
4. Show details
5. Exit

Enter your choice:  4

not enough values to unpack (expected 3, got 1)
1. Create account
2. Deposit
3. Withdraw
4. Show details
5. Exit

28. Using dictionary + exception handling, create a student management system that
can:

• Add student
• Update marks
• Delete student
• Display all Raise custom exception if student not found.