*****Pandas Challenges**
Challenge 1 – Complete Data Cleaning
Your manager gives you a messy dataset.
Perform all of the following:
• Load the dataset.
• Display dataset information.
• Find missing values.
• Remove duplicate rows.
• Fill missing values:
o Age → median
o Balance → mean
• Rename:
o Target → CustomerStatus
o AnnualIncome → Income
• Display the first 15 rows.***

In [5]:
import pandas as pd
df=pd.read_csv(r"C:\Users\jyoti\Downloads\Task_dataset.csv")#Load the dataset
print(df)
print("data loaded successfully")
df.info()#Display dataset information
print(" information of data loaded")

       CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0            10001  58.0       49184.0      2139          581        NaN
1            10002  65.0      162964.0      6197          732    6356.54
2            10003  56.0       26956.0     37281          503  143203.92
3            10004  55.0       92926.0       925          463  139627.88
4            10005  66.0      108236.0      7198          394   75985.46
...            ...   ...           ...       ...          ...        ...
1015         10450  43.0      173620.0      7121          644   60353.03
1016         10753  25.0       54490.0     13794          303  124512.07
1017         10810  49.0       82062.0     47170          813   53850.09
1018         10267  38.0           NaN     10424          722  138100.05
1019         10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
data loaded successfully
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
 nformation of data loaded

In [8]:
#finding missing values
df.isnull().sum()

 CustomerID      0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [9]:
#• Remove duplicate rows.
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [12]:
'''• Fill missing values:
o Age → median
o Balance → mean'''
# finding median of age
print("median of age is:")
median=df["Age"].median()
print(median)
# finding mean of Balance
print("mean of Balance is: ")
mean=df["Balance"].mean()
print(mean)
print("after filling missing value of Age  and Balance with its median and mean is :")
df[["Age","Balance"]].fillna(f"{mean},{median}")

median of age is:
44.0
mean of Balance is:
97523.53566563467
after filling missing value of Age  and Balance with its median and mean is :

       Age                 Balance
0     58.0  97523.53566563467,44.0
1     65.0                 6356.54
2     56.0               143203.92
3     55.0               139627.88
4     66.0                75985.46
...    ...                     ...
1015  43.0                60353.03
1016  25.0               124512.07
1017  49.0                53850.09
1018  38.0               138100.05
1019  62.0  97523.53566563467,44.0

[1020 rows x 2 columns]

In [18]:
'''• Rename:
o Target → CustomerStatus
o AnnualIncome → Income'''
df.rename(columns={"Target":"CustomerStatus","AnnualIncome":"Income"},inplace=True)

In [19]:
df.head(15)#display first 15 rows

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn

***Challenge 2 – Banking Report
The bank wants a numeric report.
Tasks
• Select only numeric columns.
• Display summary statistics.
• Convert Age and CreditScore to float.
• Display information again.***

In [27]:
numeric_columns=df.select_dtypes(include=["number"])#• Select only numeric columns.
print(numeric_columns)
numeric_columns.describe()#• Display summary statistics.
numeric_columns[["Age","CreditScore"]].astype("float")#• Convert Age and CreditScore to float.
numeric_columns.info()# Display information again

       CustomerID    Age    Income  Spending  CreditScore    Balance  Tenure
0            10001  58.0   49184.0      2139          581        NaN       2
1            10002  65.0  162964.0      6197          732    6356.54       1
2            10003  56.0   26956.0     37281          503  143203.92       8
3            10004  55.0   92926.0       925          463  139627.88       5
4            10005  66.0  108236.0      7198          394   75985.46       5
...            ...   ...       ...       ...          ...        ...     ...
1015         10450  43.0  173620.0      7121          644   60353.03       2
1016         10753  25.0   54490.0     13794          303  124512.07       4
1017         10810  49.0   82062.0     47170          813   53850.09       8
1018         10267  38.0       NaN     10424          722  138100.05       6
1019         10059  62.0   97504.0     36833          430        NaN      10

[1020 rows x 7 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   Income        967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 55.9 KB

***Challenge 3 – Duplicate Investigation
Find duplicate customers.
Then
• Count duplicate rows.
• Remove duplicates.
• Print information before and after removing duplicates.
• Show the last 20 rows.***

In [40]:
print(df[df.duplicated()])  # Find duplicate customers

print(df.duplicated().sum())  # Count duplicate rows

print("Before removing duplicates:")
df.info()

df = df.drop_duplicates()  # Remove duplicates permanently

print("After removing duplicates:")
df.info()

print(df.tail(20))  # Show last 20 rows

       CustomerID    Age    Income  Spending  CreditScore    Balance  Tenure  \
1000         10643  41.0  125012.0     18825          761   35977.85       2
1001         10763  56.0  102965.0     17517          838  115028.54       9
1002         10910  66.0  118506.0      6296          306   81892.13       4
1003         10200  19.0  115052.0     20741          484  190233.86       5
1004         10587  29.0       NaN     40255          383  168358.60       2
1005         10798  22.0  176830.0      7626          688   65481.65      10
1006         10653  32.0       NaN     21266          598  142086.70       9
1007         10756  53.0   74430.0      3705          489   29651.23      10
1008         10417  70.0   40417.0     37956          681   23880.19      10
1009         10499  34.0  166546.0     12497          643  130886.93       3
1010         10515  62.0  199762.0     41808          309   60223.29      10
1011         10457  44.0   63604.0     27633          804  176354.13       5
1012         10882  61.0  115417.0      3879          413   76591.00       7
1013         10531  64.0   85162.0     32083          654  132742.13      10
1014         10181  50.0  166466.0     44281          662   14415.10       0
1015         10450  43.0  173620.0      7121          644   60353.03       2
1016         10753  25.0   54490.0     13794          303  124512.07       4
1017         10810  49.0   82062.0     47170          813   53850.09       8
1018         10267  38.0       NaN     10424          722  138100.05       6
1019         10059  62.0   97504.0     36833          430        NaN      10

     Geography  Gender    Segment CustomerStatus
1000   Germany   Other     Retail           Stay
1001        UK     NaN        SME           Stay
1002    Canada    Male        SME          Churn
1003    Canada    Male     Retail          Churn
1004   Germany    Male  Corporate          Churn
1005    France    Male     Retail           Stay
1006    France  Female  Corporate           Stay
1007        UK    Male     Retail          Churn
1008     India    Male     Retail           Stay
1009        UK    Male        SME           Stay
1010     India   Other        SME          Churn
1011   Germany  Female     Retail           Stay
1012       NaN    Male  Corporate          Churn
1013    Canada    Male        SME           Stay
1014    Canada    Male  Corporate          Churn
1015       USA   Other  Corporate           Stay
1016     India     NaN  Corporate          Churn
1017   Germany  Female     Retail           Stay
1018   Germany   Other  Corporate           Stay
1019    Canada   Other        NaN          Churn
20
Before removing duplicates:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1020 non-null   int64
 1   Age             970 non-null    float64
 2   Income          967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   int64
 5   Balance         969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  CustomerStatus  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
After removing duplicates:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    CustomerID     1000 non-null   int64
 1   Age             950 non-null    float64
 2   Income          950 non-null    float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   int64
 5   Balance         950 non-null    float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB
      CustomerID    Age    Income  Spending  CreditScore    Balance  Tenure  \
980         10981  41.0  199633.0      8498          847  173390.59       7
981         10982  34.0   98876.0      6414          541   59484.58       2
982         10983  69.0  188933.0     27126          334        NaN       1
983         10984  44.0  107221.0     47514          732  175352.25       1
984         10985  50.0   37397.0     23559          730  120423.19       8
985         10986  62.0   27169.0      3914          488  126031.27      10
986         10987  30.0  184704.0     20524          621  115161.87       1
987         10988  63.0  190178.0      9025          720  158528.46       5
988         10989  26.0   88335.0     11869          635  159905.73       3
989         10990  29.0  123152.0     25228          884   44897.43       0
990         10991  58.0   79954.0      6331          773   39653.24       2
991         10992  45.0       NaN     17549          452   17812.25       5
992         10993  18.0  157845.0     29018          764  165451.49       7
993         10994  31.0   69950.0     17945          594  149288.61       6
994         10995  56.0   76509.0     19044          493   83666.20       6
995         10996  34.0   81731.0     40980          761  181465.65       5
996         10997  47.0   42475.0      1176          780   26640.99       5
997         10998  31.0  120531.0     46929          733  147220.82       4
998         10999  21.0   33661.0     22314          540   94186.48       5
999         11000  63.0   31930.0       851          559  100908.40       6

    Geography  Gender    Segment CustomerStatus
980    Canada    Male  Corporate           Stay
981    Canada   Other  Corporate           Stay
982    Canada  Female        SME          Churn
983       USA   Other  Corporate          Churn
984    France  Female  Corporate           Stay
985       USA    Male  Corporate          Churn
986       USA    Male        SME          Churn
987       NaN  Female        SME           Stay
988     India  Female  Corporate           Stay
989   Germany   Other        SME          Churn
990     India  Female        SME           Stay
991       USA   Other     Retail          Churn
992     India    Male        SME           Stay
993       USA  Female     Retail           Stay
994       USA    Male  Corporate          Churn
995   Germany   Other        SME           Stay
996    France  Female        SME           Stay
997     India    Male        SME           Stay
998       NaN   Other        SME           Stay
999        UK  Female        NaN           Stay

**Challenge 4 – HR Department
HR wants better column names.
Rename
CustomerID → Employee_ID
Age → EmployeeAge
Gender → EmployeeGender
AnnualIncome → Salary
Target → PromotionStatus
Then
• Add prefix
HR_
to every column.
Display 10 random records.**

In [45]:
df.rename(columns={"CustomerID":"Employee_ID","Age":"EmployeeAge","Gender":"EmployeeGender","AnnualIncome":"Salary","Target":"PromotionStatus"})

,CustomerID,EmployeeAge,Income,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [48]:
df.add_prefix("HR_")

,HR_ CustomerID,HR_EmployeeAge,HR_Income,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_CustomerStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [50]:
df.sample

<bound method NDFrame.sample of       CustomerID   EmployeeAge    Income  Spending  CreditScore    Balance  \
0           10001         58.0   49184.0      2139          581        NaN
1           10002         65.0  162964.0      6197          732    6356.54
2           10003         56.0   26956.0     37281          503  143203.92
3           10004         55.0   92926.0       925          463  139627.88
4           10005         66.0  108236.0      7198          394   75985.46
..            ...          ...       ...       ...          ...        ...
995         10996         34.0   81731.0     40980          761  181465.65
996         10997         47.0   42475.0      1176          780   26640.99
997         10998         31.0  120531.0     46929          733  147220.82
998         10999         21.0   33661.0     22314          540   94186.48
999         11000         63.0   31930.0       851          559  100908.40

     Tenure Geography EmployeeGender    Segment CustomerStatus
0         2    France           Male        SME           Stay
1         1       USA           Male        SME          Churn
2         8    Canada           Male  Corporate           Stay
3         5       NaN           Male     Retail          Churn
4         5        UK          Other  Corporate          Churn
..      ...       ...            ...        ...            ...
995       5   Germany          Other        SME           Stay
996       5    France         Female        SME           Stay
997       4     India           Male        SME           Stay
998       5       NaN          Other        SME           Stay
999       6        UK         Female        NaN           Stay

[1000 rows x 11 columns]>

**Challenge 5 – Transformation Challenge
Create
Income_in_Lakhs
Balance_in_Lakhs
SeniorCitizen
HighCreditScore
where
SeniorCitizen = Age + 0
HighCreditScore = CreditScore * 1
(No conditional statements.)**

In [60]:
df["Income_in_Lakhs"] = 0
df["Balance_in_Lakhs"] = 0
df["HighCreditScore"] = df["CreditScore"] * 1
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0    CustomerID       1000 non-null   int64
 1   EmployeeAge       950 non-null    float64
 2   Income            950 non-null    float64
 3   Spending          1000 non-null   int64
 4   CreditScore       1000 non-null   int64
 5   Balance           950 non-null    float64
 6   Tenure            1000 non-null   int64
 7   Geography         950 non-null    object
 8   EmployeeGender    950 non-null    object
 9   Segment           950 non-null    object
 10  CustomerStatus    1000 non-null   object
 11  Income_in_Lakhs   1000 non-null   int64
 12  Balance_in_Lakhs  1000 non-null   int64
 13  HighCreditScore   1000 non-null   int64
dtypes: float64(3), int64(7), object(4)
memory usage: 117.2+ KB

In [70]:
import pandas as pd
hf=pd.read_csv(r"C:\Users\jyoti\Downloads\customer_analytics.csv")
pd.to_numeric(hf["Annual_Income"], errors="coerce")

0        44033.0
1       215546.0
2       226403.0
3        87824.0
4        31570.0
          ...
2035     88530.0
2036    205738.0
2037    211994.0
2038     30105.0
2039    248332.0
Name: Annual_Income, Length: 2040, dtype: float64

**Q10. Fix Annual Income
Clean Annual_Income.
Requirements:
1. Convert invalid values to missing.
2. Convert the column to a numeric datatype.
3. Calculate the median.
4. Fill missing values using the median.
Use: pd.to_numeric(), median(), fillna(), astype()**

In [68]:
pd.to_numeric(hf["Annual_Income"], errors="coerce")

NameError: name 'hf' is not defined